/**
 * Build unified quiz data into quiz/data/*.js
 * Sources: MLN, PRM, jl (index.html), wedJfe (+ datajfe.md rebuild)
 *
 * Schema (PRM-compatible + task):
 * {
 *   id, task, taskLabel, num?,
 *   question, options: {A,B,C,...}, answer | answers[],
 *   alternatives?, explanation: {
 *     questionVi?, optionsVi?, answerDisplay?,
 *     concept?, whyCorrect?, whyWrong?: {A: string},
 *     whatIs?: {A: string},  // "Là gì?" per option
 *     memoryTip?  // optional; promt.md prefers none — keep if high quality
 *   }
 * }
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../..");
const OUT = path.resolve(__dirname, "../data");

const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

function ensureDir(d) {
  fs.mkdirSync(d, { recursive: true });
}

function writeBank(key, questions, meta = {}) {
  ensureDir(OUT);
  const payload = {
    subject: key,
    generatedAt: new Date().toISOString(),
    count: questions.length,
    ...meta,
    questions,
  };
  const jsonPath = path.join(OUT, `${key}.json`);
  const jsPath = path.join(OUT, `${key}.js`);
  fs.writeFileSync(jsonPath, JSON.stringify(payload, null, 0), "utf8");
  const js =
    `// Auto-generated by quiz/tools/build_all.mjs — do not edit by hand\n` +
    `window.QUIZ_DATA = window.QUIZ_DATA || {};\n` +
    `window.QUIZ_DATA[${JSON.stringify(key)}] = ${JSON.stringify(questions)};\n`;
  fs.writeFileSync(jsPath, js, "utf8");
  console.log(`[ok] ${key}: ${questions.length} → data/${key}.js`);
}

function stripLetterPrefix(s) {
  return String(s || "")
    .replace(/^[A-Fa-f][\.\)\:]\s*/, "")
    .trim();
}

function optionsFromArray(arr) {
  const out = {};
  (arr || []).forEach((t, i) => {
    out[LETTERS[i]] = stripLetterPrefix(t);
  });
  return out;
}

function optionsFromObject(obj) {
  const out = {};
  Object.keys(obj || {})
    .sort()
    .forEach((k) => {
      out[k.toUpperCase()] = String(obj[k] ?? "");
    });
  return out;
}

/** Pull short label + long parenthetical as explain text */
function splitParenExplain(text) {
  const s = String(text || "").trim();
  const m = s.match(/^(.*?)(\s*[\(（](.+)[\)）])\s*$/);
  if (m && m[1].trim().length >= 1 && m[3].trim().length > 8) {
    return { label: m[1].trim().replace(/[.,;:]+$/, ""), detail: m[3].trim() };
  }
  // "Đáp án: X (detail)"
  const m2 = s.match(/^Đáp án:\s*(.+?)(\s*\((.+)\))?\s*\.?$/i);
  if (m2) {
    return {
      label: m2[1].replace(/\s*\(.+$/, "").trim(),
      detail: (m2[3] || m2[1] || "").trim(),
    };
  }
  return { label: s, detail: "" };
}

function cleanOptionText(s) {
  const { label } = splitParenExplain(s);
  // if still very long polluted, take first clause before " - " with long vi
  if (label.length > 120 && label.includes(" - ")) {
    return label.split(" - ")[0].trim();
  }
  return label || String(s || "").trim();
}

function bullets(...lines) {
  return lines
    .filter(Boolean)
    .map((l) => String(l).replace(/^\s*[•\-\*]\s*/, "").trim())
    .filter(Boolean)
    .map((l) => `• ${l}`)
    .join("\n");
}

function buildWhyWrongStructured(opts, answerLetter, whatIs, whyMap) {
  const wrong = {};
  Object.keys(opts).forEach((L) => {
    if (L === answerLetter) return;
    const name = opts[L];
    const wi = (whatIs && whatIs[L]) || `Khái niệm/phương án: ${name}`;
    const why =
      (whyMap && whyMap[L]) ||
      `Sai trong ngữ cảnh câu hỏi này vì không phải đáp án đúng.`;
    wrong[L] = bullets(`Là gì? ${wi}`, `Vì sao sai? ${why}`);
  });
  return wrong;
}

// ─── PRM ───────────────────────────────────────────────
function buildPrm() {
  const raw = JSON.parse(
    fs.readFileSync(path.join(ROOT, "PRM/questions.json"), "utf8")
  );
  const qs = raw.map((q, i) => {
    const task = q.exam === "re" ? "re" : "fe";
    const taskLabel =
      q.examLabel || (task === "re" ? "SP26-B5-FE" : "SP26-FE");
    const exp = q.explanation || {};
    const explanation = {
      questionVi: exp.questionVi || "",
      optionsVi: exp.optionsVi || {},
      answerDisplay: exp.answerDisplay || "",
      concept: exp.concept || "",
      whyCorrect: exp.whyCorrect || "",
      whyWrong: exp.whyWrong || {},
      memoryTip: exp.memoryTip || undefined,
    };
    // Flex: ensure concept exists when we have whyCorrect
    if (!explanation.concept && explanation.whyCorrect) {
      const first = String(explanation.whyCorrect).split(/\n/)[0];
      explanation.concept = first
        .replace(/^【Khái niệm】/, "")
        .replace(/^•\s*/, "")
        .slice(0, 220);
    }
    return {
      id: q.id != null ? Number(q.id) : i + 1,
      task,
      taskLabel,
      num: q.num != null ? q.num : q.id,
      question: q.question,
      options: optionsFromObject(q.options),
      answer: q.answer,
      answers: q.answers,
      alternatives: q.alternatives || [],
      explanation,
      source: q.source || taskLabel,
    };
  });
  writeBank("prm", qs, { tasks: ["fe", "re"] });
}

// ─── MLN ───────────────────────────────────────────────
function buildMln() {
  const raw = JSON.parse(
    fs.readFileSync(path.join(ROOT, "MLN/questions.json"), "utf8")
  );
  const qs = raw.map((q, i) => {
    const exp = q.explanation || {};
    return {
      id: q.id != null ? Number(q.id) : i + 1,
      task: "all",
      taskLabel: "MLN",
      num: q.id != null ? q.id : i + 1,
      question: q.question,
      options: optionsFromObject(q.options),
      answer: q.answer,
      answers: q.answers,
      alternatives: q.alternatives || [],
      variantOfStem: q.variantOfStem,
      explanation: {
        questionVi: exp.questionVi || "",
        optionsVi: exp.optionsVi || {},
        answerDisplay: exp.answerDisplay || "",
        concept: exp.concept || "",
        whyCorrect: exp.whyCorrect || "",
        whyWrong: exp.whyWrong || {},
        memoryTip: exp.memoryTip || undefined,
      },
    };
  });
  writeBank("mln", qs, { tasks: ["all"] });
}

// ─── JIT / jl ──────────────────────────────────────────
function extractJsArray(html, name) {
  const markers = [`const ${name} =`, `const ${name}=`];
  let i = -1;
  for (const m of markers) {
    i = html.indexOf(m);
    if (i >= 0) break;
  }
  if (i < 0) throw new Error(`Cannot find ${name}`);
  const start = html.indexOf("[", i);
  let depth = 0;
  let end = -1;
  for (let j = start; j < html.length; j++) {
    const c = html[j];
    if (c === "[") depth++;
    else if (c === "]") {
      depth--;
      if (depth === 0) {
        end = j;
        break;
      }
    }
  }
  // eslint-disable-next-line no-new-func
  return Function(`"use strict"; return (${html.slice(start, end + 1)});`)();
}

function parseCvList(cv) {
  const opts = {};
  const optsVi = {};
  (cv || []).forEach((line, i) => {
    const L = LETTERS[i];
    const raw = String(line);
    const m = raw.match(/^([A-Fa-f])[\.\)\:]\s*(.*)$/);
    const body = m ? m[2] : stripLetterPrefix(raw);
    // SAMPLE often "収集（しゅうしゅう）：Thu thập"
    const parts = body.split(/：|:\s*/);
    if (parts.length >= 2 && /[\u3040-\u30ff\u4e00-\u9fff]/.test(parts[0])) {
      opts[L] = parts[0].trim();
      optsVi[L] = parts.slice(1).join(":").trim();
    } else {
      opts[L] = body.trim();
      optsVi[L] = body.trim();
    }
  });
  return { opts, optsVi };
}

function isMostlyJapanese(s) {
  const t = String(s || "");
  const jp = (t.match(/[\u3040-\u30ff\u4e00-\u9fff]/g) || []).length;
  return jp >= 8 && jp >= t.length * 0.25;
}

function rebuildJitExplain(q, tr, task) {
  const answer = String(q.a || "A").toUpperCase();
  const { optsVi: fromC } = parseCvList((tr && tr.cv) || q.c.map((x) => x));
  const options = optionsFromArray(q.c);
  const optionsVi = {};
  Object.keys(options).forEach((L) => {
    if (tr && tr.cv) {
      const line = tr.cv[LETTERS.indexOf(L)] || "";
      const body = stripLetterPrefix(line);
      const col = body.split(/：|:\s*/);
      if (col.length >= 2) optionsVi[L] = col[col.length - 1].trim();
      else optionsVi[L] = body;
    } else if (fromC[L]) optionsVi[L] = fromC[L];
    else optionsVi[L] = options[L];
  });

  const qv = (tr && tr.qv) || "";
  const whyRaw = (tr && tr.why) || "";
  const exJp = (q.ex || "").trim();

  let whyCorrectCore = "";
  const mWhy = whyRaw.match(/Lý do:\s*(.+?)(?:\s+Khớp|\s+Đây là|\s+So với|$)/s);
  if (mWhy) whyCorrectCore = mWhy[1].trim();
  else if (exJp) whyCorrectCore = exJp;
  else whyCorrectCore = whyRaw;

  whyCorrectCore = whyCorrectCore
    .replace(/Khớp kiến thức giáo trình[^.]*(?:\.|$)/g, "")
    .replace(/So với lựa chọn khác:.*$/s, "")
    .replace(/✓\s*Chọn\s*[A-D]\s*[—\-].*?Lý do:\s*/i, "")
    .trim();

  const ansVi = optionsVi[answer] || options[answer] || answer;
  const ansJp = options[answer] || "";

  // Concept: always Vietnamese-first (promt.md)
  const concept = bullets(
    `${ansVi}${ansJp && ansJp !== ansVi ? ` (${ansJp})` : ""} là đáp án đúng.`
  ).replace(/^•\s*/, "");

  const whyLines = [];
  whyLines.push(`Chọn ${answer} — ${ansVi}.`);
  if (qv) whyLines.push(`Câu hỏi hỏi: ${qv}`);
  if (whyCorrectCore && !isMostlyJapanese(whyCorrectCore)) {
    whyLines.push(whyCorrectCore);
  } else if (exJp) {
    whyLines.push(`Theo giáo trình (JP): ${exJp}`);
  } else if (whyCorrectCore) {
    whyLines.push(`Ghi chú: ${whyCorrectCore}`);
  }
  // Detect "chọn phát biểu SAI"
  if (/sai|正しくない|正しくないものを/i.test(q.q + qv)) {
    whyLines.push("Đây là câu tìm phát biểu SAI: đáp án là nội dung không đúng.");
  }
  const whyCorrect = bullets(...whyLines);

  const whyMap = {};
  const so = whyRaw.match(/So với lựa chọn khác:\s*(.+)$/s);
  if (so) {
    so[1].split("|").forEach((chunk) => {
      const m = chunk.trim().match(/^([A-D])\s*(.+)$/i);
      if (!m) return;
      const L = m[1].toUpperCase();
      let rest = m[2]
        .replace(/^sai\/không khớp:\s*/i, "")
        .replace(
          /^đúng\/không phải đáp án vì đây không phải phát biểu sai\s*/i,
          "Đúng nhưng không phải đáp án (câu hỏi tìm phát biểu SAI). "
        )
        .trim();
      // drop if rest is only the option text again
      if (rest && rest !== optionsVi[L] && rest !== options[L]) whyMap[L] = rest;
    });
  }

  const whatIs = {};
  Object.keys(options).forEach((L) => {
    const vi = optionsVi[L] || options[L];
    const jp = options[L];
    whatIs[L] = jp && jp !== vi ? `${vi} (JP: ${jp})` : vi;
  });

  const whyWrong = {};
  Object.keys(options).forEach((L) => {
    if (L === answer) return;
    const wi = whatIs[L];
    let reason = whyMap[L];
    if (!reason || reason === optionsVi[L] || reason === options[L]) {
      reason = `Sai trong ngữ cảnh câu hỏi này vì cần «${ansVi}», không phải «${optionsVi[L] || options[L]}».`;
    }
    whyWrong[L] = bullets(`Là gì? ${wi}`, `Vì sao sai? ${reason}`);
  });

  return {
    options,
    explanation: {
      questionVi: qv,
      optionsVi,
      answerDisplay: `${answer}. ${ansVi}`,
      concept,
      whyCorrect,
      whyWrong,
      whatIs,
    },
  };
}

function buildJit() {
  const html = fs.readFileSync(path.join(ROOT, "jl/index.html"), "utf8");
  const QUIZ = extractJsArray(html, "QUIZ");
  const SAMPLE = extractJsArray(html, "SAMPLE");
  const PT = extractJsArray(html, "PT");
  const QUIZ_TR = extractJsArray(html, "QUIZ_TR");
  const SAMPLE_TR = extractJsArray(html, "SAMPLE_TR");
  const PT_TR = extractJsArray(html, "PT_TR");

  let id = 1;
  const out = [];
  const packs = [
    { task: "quiz", label: "Quiz", bank: QUIZ, tr: QUIZ_TR },
    { task: "sample", label: "Sample", bank: SAMPLE, tr: SAMPLE_TR },
    { task: "pt", label: "Quiz PT", bank: PT, tr: PT_TR },
  ];
  for (const pack of packs) {
    pack.bank.forEach((q, idx) => {
      const tr = pack.tr[idx] || null;
      const rebuilt = rebuildJitExplain(q, tr, pack.task);
      out.push({
        id: id++,
        task: pack.task,
        taskLabel: pack.label,
        num: idx + 1,
        chapterHint: q.m,
        question: q.q,
        options: rebuilt.options,
        answer: String(q.a || "A").toUpperCase(),
        alternatives: [],
        explanation: rebuilt.explanation,
        meta: { originEx: q.ex || "" },
      });
    });
  }
  writeBank("jit", out, { tasks: ["quiz", "sample", "pt"] });
}

// ─── FE / wedJfe ───────────────────────────────────────
const DATAJFE_ANSWERS = {
  1: 3, 2: 0, 3: 0, 4: 3, 5: 3, 7: 2, 8: 0, 9: 3, 10: 2, 11: 3, 12: 3, 13: 3,
  14: 3, 15: 2, 16: 3, 17: 0, 18: 3, 19: 0, 20: 1, 21: 1, 22: 2, 23: 3, 24: 0,
  25: 3, 26: 0, 27: 0, 28: 1, 29: 2, 30: 1, 31: 0, 32: 0, 33: 0, 34: 3, 35: 2,
  36: 1, 37: 2, 38: 3, 39: 2, 40: 2, 41: 3, 44: 1,
};
const DATAJFE_SKIP = new Set([6, 42, 43]);
const DATAJFE_TIPS = {
  1: "Token ring/token bus chỉ gửi khi có token — khác CSMA/CD tranh chấp kênh.",
  2: "STEP (ISO 10303) là chuẩn trao đổi product model.",
  3: "Circuit switching: kênh dành riêng, dễ lãng phí khi traffic bursty.",
  4: "Rút ngắn activity chỉ ảnh hưởng deadline nếu nằm trên critical path.",
  5: "Tapping = nghe lén/chặn dữ liệu trên đường truyền.",
  7: "ISO 12207: khung quy trình vòng đời PM, không bắt buộc method cụ thể.",
  8: "Servlet: Java chạy trên application server, đáp request client.",
  9: "ISO/IEC 15408 Common Criteria: khung yêu cầu & đánh giá bảo mật.",
  10: "CMMI L2 Managed: quản lý theo dự án, chưa chuẩn hóa toàn tổ chức.",
  11: "Phụ thuộc transitive giữa non-key → chưa đạt 3NF.",
  12: "HDLC: frame, bit stuffing, full-duplex.",
  13: "Message digest dùng để phát hiện falsification (toàn vẹn).",
  14: "Shareware: dùng thử miễn phí, trả phí nếu tiếp tục dùng.",
  15: "ATM: cell cố định, virtual circuit, QoS.",
  16: "Message switching: store-and-forward, hỗ trợ khác tốc độ.",
  17: "Xóa nút BST thường lấy inorder successor (nhỏ nhất cây con phải).",
  18: "Message authentication phát hiện document bị sửa.",
  19: "LEFT OUTER JOIN giữ mọi dòng bảng trái.",
  20: "Scavenging: lấy residual data sau job — không phải chặn trên mạng.",
  21: "CROSS JOIN / Cartesian: mọi cặp hàng.",
  22: "Deadlock: hai transaction chờ khóa lẫn nhau.",
  23: "FDM: chia tần số; guardband giảm nhiễu.",
  24: "ADSL: Internet qua đường điện thoại, download > upload.",
  25: "Dummy activity: quan hệ phụ thuộc, thời lượng 0.",
  26: "M/M/1 giả định service time exponential.",
  27: "M/M/1 giả định FCFS; priority phá giả định.",
  28: "Ready = chờ CPU; nhiều process có thể xếp hàng ready.",
  29: "Mã hóa bằng public key người nhận → giải bằng private key người nhận.",
  30: "Linear search best case: 1 so sánh (phần tử ở đầu).",
  31: "Two-phase commit giữ toàn vẹn cập nhật phân tán.",
  32: "Hết repeated group = 1NF; partial dependency → chưa 2NF.",
  33: "Availability (CIA): truy cập thông tin khi cần.",
  34: "Data Link: frame, error detect, physical addressing.",
  35: "Định lượng hóa kiểm soát quy trình (hướng CMMI higher).",
  36: "Backward pass: lấy giá trị nhỏ hơn khi nhánh phân kỳ.",
  37: "Logical error → roll-back bằng pre-update log.",
  38: "Router: chuyển gói giữa mạng logic, tầng Network.",
  39: "FCS trong HDLC: mã kiểm soát lỗi frame.",
  40: "Khóa bí mật đối xứng phải giữ bí mật.",
  41: "Class C: host hợp lệ, không dùng .0/.255; 256 invalid.",
  44: "Ready state: chờ CPU, có thể nhiều process trong ready queue.",
};

function parseDatajfeMd(text) {
  text = text.replace(/log\s*\n\s*2\s*\n\s*.?\s*\n\s*N/gi, "log2 N");
  const parts = text.split(/(?=(?:^|\n)image(?:_\d+)?\.png)/i);
  const out = [];
  for (const p0 of parts) {
    const p = p0.trim();
    if (!p) continue;
    const mimg = p.match(/^(image(?:_\d+)?\.png)/i);
    if (!mimg) continue;
    const img = mimg[1];
    let key = 1;
    const mk = img.match(/image_(\d+)\.png/i);
    if (mk) key = Number(mk[1]);
    const rest = p.slice(mimg[0].length).trim();
    const lines = rest.split(/\r?\n/);
    let q = null;
    const opts = [];
    let i = 0;
    while (i < lines.length) {
      let line = lines[i].trim();
      if (/^Câu hỏi:|^Cau hoi:/i.test(line)) {
        q = line.replace(/^Câu hỏi:\s*|^Cau hoi:\s*/i, "").trim();
        i++;
        while (i < lines.length && !lines[i].trim()) i++;
        let buf = [];
        while (i < lines.length) {
          const s = lines[i].trim();
          if (/^image(?:_\d+)?\.png/i.test(s)) break;
          if (/^Dưới đây|^Duoi day/i.test(s)) break;
          if (!s) {
            if (buf.length) {
              opts.push(buf.join(" ").replace(/\s+/g, " ").trim());
              buf = [];
            }
            i++;
            continue;
          }
          buf.push(s.replace(/^[a-dA-D]\)\s*/, ""));
          i++;
        }
        if (buf.length) opts.push(buf.join(" ").replace(/\s+/g, " ").trim());
        break;
      }
      i++;
    }
    if (q && opts.length) {
      const norm = opts.map((o) =>
        /log\s*2\s*N|log2\s*N/i.test(o) ? "log₂ N" : o
      );
      out.push({ img, key, q, opts: norm.filter(Boolean) });
    }
  }
  return out;
}

/** Keyword contrast hints for FE wrong options (lightweight, deterministic) */
const FE_CONTRAST = [
  {
    ifAns: /circuit switching/i,
    ifOpt: /packet switching/i,
    why: "Packet switching chia sẻ kênh theo gói; không thiết lập path dành riêng trước.",
  },
  {
    ifAns: /packet switching/i,
    ifOpt: /circuit switching/i,
    why: "Circuit switching dành riêng kênh — khác mô hình gói tin.",
  },
  {
    ifAns: /token/i,
    ifOpt: /csma|collision|contend/i,
    why: "CSMA/CD dựa trên tranh chấp kênh và phát hiện va chạm, không dùng token tuần hoàn.",
  },
  {
    ifAns: /\bSTEP\b/i,
    ifOpt: /\bEDI\b/i,
    why: "EDI là trao đổi chứng từ thương mại điện tử, không phải chuẩn product model (STEP).",
  },
  {
    ifAns: /compiler|toàn bộ.*trước/i,
    ifOpt: /interpret|từng dòng|immediate/i,
    why: "Interpreter dịch/chạy từng câu lệnh; compiler dịch cả chương trình trước khi chạy.",
  },
  {
    ifAns: /waiting|blocked/i,
    ifOpt: /ready/i,
    why: "Ready = đã sẵn sàng chờ CPU; Waiting/Blocked = đang chờ I/O hoặc sự kiện.",
  },
  {
    ifAns: /ready/i,
    ifOpt: /waiting|blocked/i,
    why: "Waiting/Blocked đang chờ sự kiện; Ready chỉ chờ được cấp CPU.",
  },
  {
    ifAns: /DROP TABLE/i,
    ifOpt: /DELETE|TRUNCATE/i,
    why: "DELETE/TRUNCATE xóa dữ liệu; DROP TABLE xóa cả định nghĩa bảng.",
  },
  {
    ifAns: /Unicode/i,
    ifOpt: /ASCII/i,
    why: "ASCII hẹp (chủ yếu Latin); Unicode bao phủ đa ngôn ngữ.",
  },
  {
    ifAns: /Open-source|mã nguồn mở/i,
    ifOpt: /proprietar|closed/i,
    why: "Phần mềm đóng không cho xem/sửa/phân phối lại mã nguồn tự do như open-source.",
  },
  {
    ifAns: /tapping/i,
    ifOpt: /scaveng/i,
    why: "Scavenging lấy residual data sau xử lý; tapping là nghe lén trên đường truyền.",
  },
  {
    ifAns: /scaveng/i,
    ifOpt: /tapping/i,
    why: "Tapping chặn trên đường truyền; scavenging thu thập dữ liệu còn sót sau job.",
  },
  {
    ifAns: /3NF|third normal/i,
    ifOpt: /2NF|1NF/i,
    why: "Các dạng chuẩn thấp hơn chưa loại hết phụ thuộc transitive giữa non-key.",
  },
  {
    ifAns: /router/i,
    ifOpt: /hub|switch|bridge/i,
    why: "Hub/switch/bridge chủ yếu tầng thấp hơn; router định tuyến giữa mạng logic (Network).",
  },
];

function feExplain({ question, options, answer, tip, detail, questionVi }) {
  const ans = answer;
  const ansText = options[ans];
  const detailClean = String(detail || "")
    .replace(/^Đáp án:\s*/i, "")
    .trim();

  const concept = tip
    ? tip
    : detailClean
      ? detailClean.length > 220
        ? detailClean.slice(0, 220) + "…"
        : detailClean
      : `${ansText} là đáp án đúng cho câu hỏi.`;

  const whyCorrect = bullets(
    `Chọn ${ans} — ${ansText}.`,
    detailClean && detailClean !== ansText ? detailClean : null,
    tip && tip !== detailClean && tip !== concept ? tip : null
  );

  const whatIs = {};
  const whyMap = {};
  Object.keys(options).forEach((L) => {
    whatIs[L] = options[L];
    if (L === ans) return;
    let reason = `Sai trong ngữ cảnh câu hỏi này vì cần «${ansText}», không phải «${options[L]}».`;
    for (const rule of FE_CONTRAST) {
      if (rule.ifAns.test(ansText + " " + (detailClean || "")) && rule.ifOpt.test(options[L])) {
        reason = rule.why;
        break;
      }
    }
    // numeric garbage / cross-question junk often short weird tokens
    if (/^\d+(\.\d+)?$/.test(options[L].trim())) {
      reason =
        "Sai trong ngữ cảnh câu hỏi này — giá trị số không liên quan tới khái niệm được hỏi.";
    }
    whyMap[L] = reason;
  });

  const whyWrong = buildWhyWrongStructured(options, ans, whatIs, whyMap);
  const optionsVi = { ...options };

  return {
    questionVi: questionVi || "",
    optionsVi,
    answerDisplay: `${ans}. ${ansText}`,
    concept,
    whyCorrect,
    whyWrong,
    whatIs,
  };
}

function loadWedQuiz() {
  const raw = fs.readFileSync(path.join(ROOT, "wedJfe/js/data-quiz.js"), "utf8");
  const m = raw.match(/window\.QUIZ_DATA\s*=\s*(\[[\s\S]*\])\s*;?\s*$/m);
  if (!m) throw new Error("Cannot parse wedJfe data-quiz.js");
  // eslint-disable-next-line no-new-func
  return Function(`"use strict"; return (${m[1]});`)();
}

function rebuildFromExistingFe(item, task) {
  const rawOpts = item.options || [];
  const cleaned = rawOpts.map((o) => cleanOptionText(o));
  // recover explain from polluted correct option or explanation field
  const ci = item.correctIndex;
  const rawCorrect = rawOpts[ci] || "";
  const { label: correctLabel, detail: fromOpt } = splitParenExplain(rawCorrect);
  const fromExp = splitParenExplain(item.explanation || item.answerText || "");
  const detail = fromOpt || fromExp.detail || fromExp.label || "";
  const options = {};
  cleaned.forEach((t, i) => {
    options[LETTERS[i]] = t || `Option ${LETTERS[i]}`;
  });
  // ensure correct option uses clean short label
  if (correctLabel) options[LETTERS[ci]] = correctLabel;

  const answer = LETTERS[ci];
  // detect scrambled: wrong options look numeric while Q is conceptual, etc. — still keep
  const explanation = feExplain({
    question: item.question,
    options,
    answer,
    tip: "",
    detail,
    questionVi: "",
  });
  // If detail is good, put as concept
  if (detail) {
    explanation.concept = detail.length > 200 ? detail.slice(0, 200) + "…" : detail;
  }
  return {
    question: item.question,
    options,
    answer,
    explanation,
    originId: item.id,
  };
}

function buildFe() {
  const existing = loadWedQuiz();
  let id = 1;
  const out = [];

  // 1) test + bank300 from existing (cleaned)
  for (const item of existing) {
    const src = item.source || "test";
    if (src === "datajfe") continue; // rebuild from md
    const task = src === "bank300" ? "bank300" : "test";
    const taskLabel = task === "bank300" ? "300 câu" : "Test";
    const rebuilt = rebuildFromExistingFe(item, task);
    // Skip empty/broken
    if (!rebuilt.question || Object.keys(rebuilt.options).length < 2) continue;
    out.push({
      id: id++,
      task,
      taskLabel,
      num: id - 1,
      question: rebuilt.question,
      options: rebuilt.options,
      answer: rebuilt.answer,
      alternatives: [],
      explanation: rebuilt.explanation,
      meta: { originId: rebuilt.originId, cleaned: true },
    });
  }

  // 2) datajfe from markdown (gold source for options)
  const md = fs.readFileSync(path.join(ROOT, "datajfe.md"), "utf8");
  const blocks = parseDatajfeMd(md);
  let n = 0;
  for (const b of blocks) {
    if (DATAJFE_SKIP.has(b.key)) continue;
    if (!(b.key in DATAJFE_ANSWERS)) {
      console.warn("[datajfe] no answer map for key", b.key);
      continue;
    }
    const ci = DATAJFE_ANSWERS[b.key];
    if (ci < 0 || ci >= b.opts.length) {
      console.warn("[datajfe] bad index", b.key, ci, b.opts.length);
      continue;
    }
    const options = optionsFromArray(b.opts);
    const answer = LETTERS[ci];
    const tip = DATAJFE_TIPS[b.key] || "";
    const explanation = feExplain({
      question: b.q,
      options,
      answer,
      tip,
      detail: tip,
      questionVi: "", // EN exam style — VI filled lightly via tip in concept
    });
    // bilingual-ish: put tip as concept + questionVi empty; optionsVi = options
    explanation.questionVi = ""; // keep EN as primary for FE
    n++;
    out.push({
      id: id++,
      task: "datajfe",
      taskLabel: "datajfe",
      num: n,
      question: b.q,
      options,
      answer,
      alternatives: [],
      explanation,
      meta: { imageKey: b.key, img: b.img },
    });
  }

  writeBank("fe", out, {
    tasks: ["test", "bank300", "datajfe"],
    note: "test/bank300: options cleaned from legacy; datajfe rebuilt from datajfe.md",
  });
}

// ─── main ──────────────────────────────────────────────
function main() {
  console.log("Building unified quiz data…");
  buildPrm();
  buildMln();
  buildJit();
  buildFe();
  // catalog
  const catalog = {
    generatedAt: new Date().toISOString(),
    subjects: ["prm", "mln", "jit", "fe"],
  };
  fs.writeFileSync(path.join(OUT, "catalog.json"), JSON.stringify(catalog, null, 2));
  console.log("Done.");
}

main();
