/** Auto-generated remaining JIT option stubs */
export const JIT_STUB_VI = {
  "枠": "khung / ô",
  "差": "hiệu / sai khác",
  "変換": "biến đổi / chuyển đổi",
  "電極": "điện cực",
  "音声": "âm thanh",
  "波長": "bước sóng",
  "名前": "tên",
  "住所": "địa chỉ",
  "最大": "lớn nhất",
  "平均": "trung bình",
  "最小": "nhỏ nhất",
  "可変": "biến thiên",
  "対数": "logarit",
  "素数": "số nguyên tố",
  "倍数": "bội số",
  "行為": "hành vi",
  "もの": "vật / đối tượng",
  "病気": "bệnh",
  "メリ": "(mảnh từ)",
  "壁紙": "hình nền",
  "石板": "bảng đá",
  "余裕": "dư / biên độ",
  "中核": "lõi / trung tâm",
  "不足": "thiếu",
  "発注": "đặt hàng",
  "偽る": "giả mạo",
  "肝心": "then chốt",
  "直径": "đường kính",
  "予備": "dự phòng",
  "実数": "số thực",
  "記号": "ký hiệu",
  "強弱": "cường độ (mạnh–yếu)",
  "音源": "nguồn âm",
  "付着": "bám dính",
  "競う": "cạnh tranh",
  "仲介": "trung gian",
  "迷う": "nhầm / lúng túng",
  "索引": "chỉ mục",
  "挿入": "chèn",
  "実体": "thực thể",
  "金銭": "tiền bạc",
  "正弦波": "sóng sine",
  "数値量": "đại lượng số",
  "紀元前": "trước Công nguyên",
  "ポンド": "pound",
  "メモリ": "bộ nhớ",
  "ハット": "dấu mũ (^)",
  "羊皮紙": "da dê (giấy cổ)",
  "携わる": "tham gia",
  "手軽に": "dễ dàng",
  "金属線": "dây kim loại",
  "未承諾": "chưa đồng ý",
  "放熱板": "tản nhiệt",
  "単純な": "đơn giản",
  "対応表": "bảng tương ứng",
  "走査線": "đường quét",
  "汎用性": "tính đa dụng",
  "ループ": "vòng lặp",
  "通信速度": "tốc độ truyền",
  "検索時間": "thời gian tìm kiếm",
  "階段構造": "cấu trúc bậc thang",
  "段階構造": "cấu trúc giai đoạn",
  "改装構造": "cấu trúc cải tạo",
  "分散処理": "xử lý phân tán",
  "ナンバー": "số",
  "仮想記憶": "bộ nhớ ảo",
  "集積線路": "mạch tích hợp (sai từ)",
  "にんすう": "số người",
  "らんすう": "số ngẫu nhiên",
  "ふっかつ": "phục hồi",
  "ふみだい": "bệ / bước đệm",
  "ドロップ": "drop",
  "化石燃料": "nhiên liệu hóa thạch",
  "はぐるま": "bánh răng",
  "保護する": "bảo vệ",
  "遠隔操作": "điều khiển từ xa",
  "商品開発": "phát triển sản phẩm",
  "ワクチン": "vaccine (chống malware)",
  "解釈する": "giải thích",
  "搭載する": "tích hợp",
  "記録媒体": "phương tiện ghi",
  "抜き出す": "trích / rút ra",
  "嗅覚装置": "thiết bị khứu giác",
  "転置式暗号": "mã hoán vị",
  "公開鍵暗号": "mật mã khóa công khai",
  "親子的表現": "biểu diễn cha–con",
  "覚えやすい": "dễ nhớ",
  "登録が義務": "bắt buộc đăng ký",
  "許可が必要": "cần phép",
  "制御コード": "mã điều khiển",
  "圧縮コード": "mã nén",
  "そいんすう": "ước số",
  "ぞうしょく": "nhân lên",
  "抵抗膜方式": "cảm ứng điện trở",
  "画面解像度": "độ phân giải màn hình",
  "フォント名": "tên font",
  "圧縮の別名": "tên khác của nén",
  "公開鍵方式": "cách khóa công khai",
  "メガバイト": "megabyte",
  "画素の色と形": "màu và hình pixel",
  "画像の解像度": "độ phân giải ảnh",
  "手続きが必要": "cần thủ tục",
  "ミドルウェア": "middleware",
  "必ず無線だけ": "chỉ không dây (tuyệt đối)",
  "ランレングス": "run-length",
  "音 - 画像": "âm – ảnh",
  "記憶アドレス": "địa chỉ nhớ",
  "静電容量方式": "cảm ứng điện dung",
  "正常終了のみ": "chỉ kết thúc bình thường",
  "紙の印刷のみ": "chỉ in giấy",
  "電源ユニット": "bộ nguồn (PSU)",
  "画面の解像度": "độ phân giải màn hình",
  "プロジェクタ": "máy chiếu",
  "ランサムウェア": "ransomware",
  "有効期限がない": "không có hạn",
  "機械を必ず使う": "luôn dùng máy",
  "入力を反転する": "đảo input (NOT)",
  "大規模集積線路": "LSI (mạch tích hợp quy mô lớn)",
  "ヘッド、テープ": "head, tape",
  "テープ、メモリ": "tape, memory",
  "ヘッド、メモリ": "head, memory",
  "計画通りの更新": "cập nhật đúng kế hoạch",
  "決済（支払い）": "thanh toán",
  "鍵が不要な暗号": "mật mã không cần khóa",
  "必ず木構造のみ": "chỉ cấu trúc cây",
  "マイク（入力）": "micro (input)",
  "ポータルサイト": "portal",
  "右肩上がりの直線": "đường thẳng dốc lên",
  "色がいくつ並ぶか": "có bao nhiêu màu liền",
  "衛星を使った通話": "gọi qua vệ tinh",
  "登録が必要である": "cần đăng ký",
  "保存容量の大きさ": "dung lượng lưu",
  "ラム (RAM)": "RAM",
  "通信速度の高速化": "tăng tốc truyền",
  "因数（いんすう）": "thừa số",
  "音程だけが変わる": "chỉ đổi cao độ",
  "電源コードの製造": "sản xuất dây nguồn",
  "画像の解像度規格": "chuẩn độ phân giải ảnh",
  "誤り検出・訂正機構": "cơ chế phát hiện/sửa lỗi",
  "階乗（かいじょう）": "giai thừa",
  "乗算（じょうざん）": "phép nhân",
  "累乗（るいじょう）": "lũy thừa",
  "上流から下流の方向": "hướng thượng nguồn → hạ nguồn",
  "下流から上流の方向": "hướng hạ nguồn → thượng nguồn",
  "マイクロプロセッサ": "vi xử lý",
  "階層型（ツリー型）": "kiểu phân cấp (cây)",
  "情報家電・家電製品": "thiết bị thông tin / gia dụng",
  "意図的な難読化のみ": "chỉ làm khó đọc có chủ đích",
  "音声WAV固定のみ": "chỉ WAV cố định",
  "テキストCSVのみ": "chỉ text/CSV",
  "斜体（イタリック）": "chữ nghiêng (italic)",
  "ベンチマークテスト": "benchmark",
  "安全保護の原則がある": "có nguyên tắc bảo vệ an toàn",
  "個人参加の原則がある": "có nguyên tắc tham gia cá nhân",
  "原文を原文に戻すこと": "khôi phục bản gốc",
  "動画配信のための規格": "chuẩn phân phối video",
  "機械語に近い低級言語": "ngôn ngữ bậc thấp gần máy",
  "余弦波 - よげんは": "sóng cosine",
  "マイクロプロセッサー": "vi xử lý",
  "ヒット商品だけを扱う": "chỉ bán hàng bán chạy",
  "非圧縮RAW必須のみ": "chỉ bắt buộc RAW không nén",
  "利用無制限の原則がある": "có nguyên tắc dùng không giới hạn",
  "氏名や生年月日を避ける": "tránh họ tên/ngày sinh",
  "密結合マルチプロセッサ": "đa xử lý liên kết chặt",
  "疎結合マルチプロセッサ": "đa xử lý liên kết lỏng",
  "正弦波 - せいげんは": "sóng sine",
  "正玄波 - せいげんは": "sóng sine (viết sai)",
  "ヘッド、テープ、メモリ": "head, tape, memory",
  "店舗面積を必ず拡大する": "luôn mở rộng diện tích cửa",
  "フィッシングに注意する": "cẩn thận phishing",
  "不審なリンクに注意する": "cẩn thận link đáng ngờ",
  "保守性・可読性・拡張性": "bảo trì · dễ đọc · mở rộng",
  "文書を一切残さないこと": "không để lại tài liệu",
  "画像を圧縮するための変換": "biến đổi để nén ảnh",
  "音の波としての性質を使う": "dùng tính chất sóng âm",
  "白と黒が多い画像に効果的": "hiệu quả với ảnh nhiều trắng đen",
  "公開鍵を使って暗号化する": "mã hóa bằng khóa công khai",
  "技術の進歩を保護する権利": "quyền bảo hộ tiến bộ kỹ thuật",
  "工業の進歩を保護する権利": "quyền bảo hộ tiến bộ công nghiệp",
  "通信速度を測る単位である": "là đơn vị đo tốc độ truyền",
  "暗号化の方式の1つである": "là một cách mã hóa",
  "正弦波 - しょうげんは": "sóng sine (đọc sai)",
  "古いブラウザを使い続ける": "cứ dùng trình duyệt cũ",
  "一般の電話回線を使った通話": "gọi qua đường điện thoại thường",
  "文字を別の文字に置き換える": "thay chữ bằng chữ khác",
  "桁数の多い数字の並びである": "dãy số nhiều chữ số",
  "誤りを検出も訂正もできない": "không phát hiện/sửa lỗi được",
  "単一企業のLANの別名のみ": "chỉ là tên khác LAN một doanh nghiệp",
  "大文字と小文字を組み合わせる": "kết hợp chữ hoa và thường",
  "自分の電話番号をそのまま使う": "dùng nguyên số điện thoại của mình",
  "パソコンの電源を管理する基板": "bo mạch quản lý nguồn PC",
  "許可を得てから権利が発生する": "có quyền sau khi được phép",
  "最も複雑な画像圧縮方式の1つ": "một cách nén ảnh phức tạp nhất",
  "製品のデザインについての権利": "quyền về thiết kế sản phẩm",
  "個人のパソコンをねらった犯罪": "tội nhắm PC cá nhân",
  "個人情報の取り扱いに注意する": "cẩn thận xử lý thông tin cá nhân",
  "圧縮すると音質は必ず変わらない": "nén thì chất lượng âm không đổi (sai)",
  "汎用性や読みやすさに問題がある": "có vấn đề đa dụng/dễ đọc",
  "音の振幅をより細かく記録できる": "ghi biên độ âm chi tiết hơn",
  "必ず機械語そのものを手書きする": "luôn viết tay ngôn ngữ máy",
  "公開鍵と秘密鍵が必ず同一文字列": "khóa công khai và bí mật luôn giống nhau",
  "メモリ (Bộ nhớ RAM)": "bộ nhớ RAM",
  "創作した時点で自動的に権利が発生": "có quyền tự động khi sáng tạo",
  "稼働率 ＝ MTBF × MTTR": "Availability = MTBF × MTTR (thường sai)",
  "稼働率 ＝ MTTR / MTBF": "Availability = MTTR / MTBF (thường sai)",
  "音声の波をそのまま電波で送受信する": "gửi/nhận sóng âm bằng sóng radio nguyên dạng",
  "通信者同士が共通に持つ乱数表を使う": "dùng bảng số ngẫu nhiên chung",
  "汎用性や読みやすさに問題があります": "có vấn đề đa dụng/dễ đọc",
  "低い周波数は元の波の大きな性質を表す": "tần số thấp thể hiện tính chất lớn của sóng gốc",
  "創作した時点で自動的に権利が発生する": "có quyền tự động khi sáng tạo",
  "文字を何文字かずらすことで暗号化する": "mã hóa bằng cách dịch vài ký tự",
  "ブログやウィキ（Wiki）などの活用": "dùng blog/Wiki…",
  "ヘッドは常にディスク面に接触している": "head luôn chạm mặt đĩa",
  "常に最新版に更新されるブラウザを使う": "dùng trình duyệt luôn cập nhật",
  "暗号化と復号に同じ鍵を使う共通鍵暗号": "mật mã khóa chung (cùng khóa mã/giải)",
  "楽器演奏の命令をデジタルで伝達する規格": "chuẩn truyền lệnh nhạc số (MIDI)",
  "通信者同士が共通に持つ乱数表などを使う": "dùng bảng số ngẫu nhiên chung…",
  "新規の技術についての権利を保護する権利": "quyền bảo hộ kỹ thuật mới (sáng chế)",
  "未知の添付ファイルを無条件に開いてよい": "mở file đính kèm lạ không điều kiện (sai)",
  "通信の開始から終了までの手順を管理する。": "quản lý thủ tục từ đầu đến hết phiên",
  "フォルダはファイルのサブファイルである。": "thư mục là subfile của file (sai)",
  "演算装置と制御装置の機能が組み込まれている": "có ALU và control unit",
  "入力装置と出力装置の機能が組み込まれている": "có input và output unit",
  "命令を解釈し、他の装置に制御信号を送ること": "giải mã lệnh, gửi tín hiệu điều khiển",
  "演算装置と制御装置の処理速度を向上させること": "tăng tốc ALU và control unit",
  "在庫を一切持たないことが必須条件で唯一の定義": "không tồn kho là điều kiện duy nhất (sai)",
  "プロセス・メモリ・ファイル・入出力などの管理": "quản lý process/memory/file/I/O",
  "事故の代表的なものはハードウェアの故障です。": "sự cố điển hình là hỏng phần cứng",
  "人間が理解しやすい文法でプログラムを記述できる": "viết chương trình bằng ngữ pháp dễ hiểu",
  "画素数 ≒ (cm/2.54×dpi) の縦×横": "số pixel ≈ (cm/2.54×dpi) dọc×ngang",
  "電流が流れる方向と電子の移動する方向は逆である。": "chiều dòng và chiều electron ngược nhau",
  "ファイルを整理して格納する入れ物（ディレクトリ）": "hộp chứa file (thư mục/directory)",
  "exe,vbs,scr,pif の添付をすぐに開く": "mở ngay file đính kèm exe/vbs/scr/pif (nguy hiểm)",
  "日本語はASCII 7ビットだけで完全に表現できる": "tiếng Nhật biểu diễn đủ bằng ASCII 7-bit (sai)",
  "ネットワーク型データモデルなど網状の関係を表す表現": "biểu diễn quan hệ dạng mạng (network model)",
  "音声を圧縮するには，音の波としての性質を使います。": "nén âm dùng tính chất sóng âm",
  "伝染し、潜伏期間をおいて発病する過程が生物のウィルス": "lây → ủ → phát bệnh như virus sinh học",
  "プログラムの基本的な処理の手順をアルゴリズムと言います。": "thuật toán = trình tự xử lý cơ bản của chương trình",
  "ネットワーク接続手段として無線通信の重要性が増しています。": "truyền không dây ngày càng quan trọng",
  "コンピュータの基本回路の 1 つに OR 回路があります。": "mạch OR là một mạch cơ bản của máy tính",
  "画像ではフーリエ変換以外の方法でも圧縮することができます。": "ảnh có thể nén bằng cách khác Fourier",
  "デジタル画像は縦横に並んだ点の集まりとして表現されています。": "ảnh số = tập điểm xếp dọc/ngang",
  "SQL は人工的な言語であり，構文や単語が定義されています。": "SQL là ngôn ngữ nhân tạo có cú pháp/từ định nghĩa",
  "最近の暗号では，コンピュータを使って暗号化，復号化を行います。": "mật mã hiện đại mã/giải bằng máy tính",
  "通信相手までのデータの轉送経路を決定し、論理アドレスを管理する。": "chọn đường truyền và quản lý địa chỉ logic",
  "ウイルス対策ソフトを購入し、パターンファイルを日常的に更新する。": "mua antivirus và cập nhật pattern hằng ngày",
  "送信者Aは、受信者Bの秘密鍵を使って文書を暗号化し、Bに送付する。": "A mã bằng khóa bí mật của B rồi gửi (sai/đúng tùy ngữ cảnh)",
  "少数のヒット商品だけでなく多品種少量のニッチ商品も売上げに寄与する": "không chỉ hit; hàng niche cũng đóng góp (long tail)",
  "コンピュータが従うべきデータ転送規約のことをプロトコルといいます。": "protocol = quy ước truyền dữ liệu máy tuân theo",
  "対応表にない大きな数字については簡単な計算で変換することができます。": "số lớn ngoài bảng có thể đổi bằng phép tính đơn giản",
  "射影の結果を並べ替えるには ORDER BY という単語を使います。": "sắp xếp kết quả projection bằng ORDER BY",
  "通信媒体を通じてビット信号を伝送するための電気的・機械的規格を定める。": "quy định chuẩn điện/cơ để truyền bit trên môi trường",
  "ユーザインタフェースOS の機能の第 1 は，操作性を決めることです。": "UI: chức năng OS đầu là quyết định tính dễ dùng",
  "シェアウェアは無料で入手できるが、継続使用に登録と料金が必要な場合がある": "shareware: dùng thử miễn phí, tiếp tục thường phải trả",
  "一度暗号化された文書は、送信者Aも受信者Bの公開鍵を使えば復号化できる。": "A cũng giải bằng khóa công khai của B (sai điển hình)",
  "同一トラック上にデータがあるとアームを動かす必要がなく高速に読み書きできる": "cùng track → không cần di chuyển arm → đọc/ghi nhanh",
  "ダイオードは、p型とn型という2つの同じ性質の物質を貼り合わせて作られる。": "diode ghép hai vật cùng tính p và n (sai — khác tính)",
  "HTML = Hyper Text Markup Language の略。": "HTML = Hyper Text Markup Language (sai từ — HyperText)",
  "コンピュータは on と off の 2 つの状態によって処理を行います。": "máy tính xử lý bằng hai trạng thái on/off",
  "ウイルスに感染した場合は、すぐに全てのファイルを消去しパソコンを初期化する。": "nhiễm virus thì xóa hết file và reset (quá cực đoan)",
  "ウイルス感染を防ぐには、メールの利用を完全に停止することが最も効果的である。": "ngừng hẳn email là cách phòng virus hiệu quả nhất (sai)",
  "ダイオードでは、電子がp型からn型に移動しやすく、その逆方向に電流が流れる。": "electron dễ từ p→n; dòng ngược chiều (cần đối chiếu chuẩn)",
  "LEDは一般のダイオードとは構造が異なり、光を発しないという点で区別される。": "LED khác diode thường vì không phát sáng (sai — LED phát sáng)",
  "ダイオードは、電流を一方向にしか流さないという点で、真空管と異なる機能を持つ。": "diode chỉ cho dòng một chiều — khác ống chân không",
  "n型半導体は電子が不足しており、p型半導体は電子が過剰であるため安定している。": "n thiếu electron, p thừa electron (sai — ngược bản chất)",
  "LANにはコンピュータやプリンタのみが接続され、家電製品が接続されることはない。": "LAN chỉ PC/máy in, không có gia dụng (sai hiện đại)",
  "CALSのもともとの目的は、自動車業界のサプライチェーン効率化を図ることだった。": "CALS ban đầu nhằm chuỗi cung ứng ô tô (sai — quân sự)",
  "CALSを導入した結果、軍事産業を除く多くの業界で納期の長期化が報告されている。": "sau CALS nhiều ngành kéo dài giao hàng (sai)",
  "CALSは、企業間で同じデータを用いて取引できるようにするための標準規格である。": "CALS = chuẩn để doanh nghiệp giao dịch cùng dữ liệu",
  "通信途中で暗号文が盗まれても、第三者はBの公開鍵を入手すれば文書を復号化できる。": "có khóa công khai B là giải được bản mã (sai)",
  "OS は， 家電製品からスーパーコンピュータまで， 多くの機器で使われています。": "OS dùng từ gia dụng đến supercomputer",
  "汎用性の高い手続型のプログラミング言語では，処理を逐一記述しなければなりません。": "ngôn ngữ thủ tục đa dụng phải mô tả xử lý từng bước",
  "通常、新しく作成するファイルは「C:Windows」フォルダに自動的に保存される。": "phát biểu về file/thư mục",
  "ダイオードは、p型からn型に電子が移動するため、p型からn型の方向に電流が流れる。": "phát biểu về diode",
  "既知のウイルスのみを検出するよう、ウイルス対策ソフトのパターンファイルは更新しない。": "phát biểu về virus / chống malware",
  "個人のパソコンをねらった犯罪としてはウィルス(コンピュータウィルス) が代表的です。": "phát biểu về virus / chống malware",
  "半導体メモリ，もしくは単純にメモリと呼ばれるものには RAM とROM があります。": "phát biểu về CPU / bộ nhớ / bán dẫn",
  "Webサーバがブラウザに保存させる小さなデータで状態管理等に使う（適切な説明の組合せ）": "phát biểu về web",
  "ヘッドとディスク面は常に接触しており、これによってデータの読み書きの信頼性を高めている。": "phát biểu về ổ cứng",
  "オープンループ型の電子マネーは、設備投資が少なく、銀行の負担が軽いため、早期に普及した。": "phát biểu về tiền điện tử",
  "パソコンのカタログを見てみると，仕様の欄には細かい数字や聞き慣れない用語が並んでいます。": "catalogue PC ghi thông số kỹ thuật",
  "デスクトップパソコンの蓋を開けてみると図 53 のように様々な部品を見ることができます。": "mở nắp PC desktop thấy linh kiện",
  "パラパラ漫画では，少しずつ違う絵を速い速度で切り替えることで連続した画像に見せています。": "ví dụ animation từng khung (parallax/flip)",
  "LANは、広域な地域を結ぶ大規模なネットワークであり、インターネットはWANの一種である。": "phát biểu về LAN/WAN",
  "データの形式（文字コードや暗号化など）を変換し、アプリケーション層が扱える形式に変換する。": "phát biểu về mã hóa / khóa",
  "新たにパソコンを購入するときの大きな選択は Windows にするか Mac にするかです。": "phát biểu về SQL / CSDL",
  "データベースとは大量のデータを保存，管理でき，データの検索，書き換えが容易に行えるものです。": "CSDL: lưu/quản lý/tìm/sửa dữ liệu dễ",
  "関係的表現の数学的基礎はエドガー・フランク・.コッドによって 1970 年頃に研究されました。": "cơ sở toán relational model (Codd)",
  "C++や Java などの高級言語で使われるプログラミング言語の文法の基礎について説明します。": "phát biểu về thuật toán / lập trình",
  "たくさんの種類のあるコンピュータを一言で表すと「記憶」して「処理」する機械と言うことができます。": "máy tính = máy «nhớ» và «xử lý»",
  "事故や犯罪による問題点を踏まえた上で，個人がパソコンを利用するときに注意すべきことをまとめます。": "phát biểu về bảo mật / tấn",
  "LANは、ネットワーク管理者が歩いて機器の状態をチェックできる程度の局所的な範囲を指すことが多い。": "phát biểu về LAN/WAN",
  "フォルダとは， ファイルを整理するための入れ物のことで， 図 6 のようなアイコンで表現されます。": "phát biểu về file/thư mục",
  "プログラミング言語とは，コンピュータに対する命令記述の集まりであって，人工的な文法規則を持ちます。": "phát biểu về thuật toán / lập trình",
  "プログラムは内部的にはメモリに記憶されますが， メモリ上ではデータもプログラムも区別がありません。": "phát biểu về thuật toán / lập trình",
  "クローズドループ型の電子マネーでは、店舗が受け取ったバリューは発行元を通じて銀行口座に振り込まれる。": "phát biểu về tiền điện tử",
  "エクスプローラで表示される階層構造のことをディレクトリ構造と呼び、フォルダは親子関係で構成されている。": "phát biểu về file/thư mục",
  "ハードディスクへの物理的な衝撃は、ヘッドとディスクの間に隙間ができるため、読み書き速度の向上に役立つ。": "phát biểu về ổ cứng",
  "Web2.0 の考え方によると， インターネットに接続することで様々なサービスを受けることができます。": "phát biểu về web",
  "携帯電話には，電話以外にもたくさんの機能があり，中でも多くの人が利用するのがワンセグテレビの機能です。": "phát biểu về điện thoại di động",
  "CPU には Intel 社の Core i7，Core 2 Duo，ATOM などの種類があります。": "phát biểu về CPU / bộ nhớ / bán dẫn",
  "電子マネーには IC カードを使ったもの， インターネットを使ったもの， またその複合の形態があります。": "phát biểu về tiền điện tử",
  "引き算の実現には引き算回路を新たに作るのではなく，数字を負の表現にすることで足し算回路に帰着しています。": "phát biểu về phép tính / bù 2",
  "アルゴリズムを図形と矢印で表現したものをフローチャート(流れ図)と言い，直観的な理解のために使われます。": "phát biểu về thuật toán / lập trình",
  "LANとWANの区別は明確で、一つの企業内のネットワークは、支店が複数あっても常にLANとして分類される。": "phát biểu về LAN/WAN",
  "ファイルを探しやすくするためには、1つのフォルダに数百個以上のファイルをまとめて保存するのが効率的である。": "phát biểu về file/thư mục",
  "コンピュータは，演算装置，記憶装置，制御装置，入力装置，出力装置の 5 要素からなります（ 図 52 ）。": "phát biểu về CPU / bộ nhớ / bán dẫn",
  "MIDI は音楽のための特殊なコードであり，一般の音声の場合には音符のようにコード化することはできません。": "phát biểu về đa phương tiện / nén",
  "リング型は、データが隣接するノードを順次伝送され、一部のコンピュータが故障すると通信に支障が出る可能性がある": "phát biểu về topology mạng",
  "同一トラック上にデータが配置されている場合、アームを動かす必要がないため、高速に読み書きを行うことができる。": "cùng track → đọc/ghi nhanh hơn",
  "ワープロで作成した文書やその他のアプリケーションで作成したデータはファイルという形で記録媒体に保存されます。": "phát biểu về file/thư mục",
  "広域ネットワークのことを WAN と言いますが，広域と言っても通常は地域の中，国の中などの範囲に限られます。": "phát biểu về LAN/WAN",
  "与えられた原文が推測できないように変換することを暗号化と言い，原文に戻すことを復号化と言います（図 38）。": "phát biểu về mã hóa / khóa",
  "受信者Bは、暗号化用の公開鍵と復号化用の秘密鍵の両方を所持しており、Aから送られてきた文書を秘密鍵で復号する。": "phát biểu về mã hóa / khóa",
  "ネットワークの中で処理を行うコンピュータの配置は， 集中処理システムと分散処理システムに分けることができます。": "phát biểu về topology mạng",
  "通常，暗号化して送る側と，受け取って復号化する側は，共通の鍵を持ち，他人に知られないようにして通信しています。": "phát biểu về mã hóa / khóa",
  "会社などの組織で最も重要な情報を持っているサーバは攻撃対象となりやすく，犯罪者はサーバへの不正侵入を試みます。": "phát biểu về bảo mật / tấn",
  "CPU の動作原理は，電子式計算機の登場以前に数学的な概念として提唱されたチューリングマシンに基づいています。": "phát biểu về CPU / bộ nhớ / bán dẫn",
  "従来のホームページは，専門知識を持った人が発信する一方向的な情報メディアでしたが， Blog(weB LOG)…": "phát biểu về web",
  "ネットワークにおけるコンピュータの接続形態には大きく分けて， バス型， スター型，リング型の 3 種類があります。": "phát biểu về topology mạng",
  "Aさんは自身の秘密鍵で文書を暗号化して送信する。BさんはAさんの公開鍵で復号できれば、Aさんからの送信と確認できる。": "phát biểu về mã hóa / khóa",
  "Aさんは自身の公開鍵で文書を暗号化して送信する。BさんはAさんの秘密鍵で復号できれば、Aさんからの送信と確認できる。": "phát biểu về mã hóa / khóa",
  "AさんはBさんの公開鍵で文書を暗号化して送信する。Bさんは自身の秘密鍵で復号できれば、Aさんからの送信と確認できる。": "phát biểu về mã hóa / khóa",
  "AさんはBさんの秘密鍵で文書を暗号化して送信する。Bさんは自身の公開鍵で復号できれば、Aさんからの送信と確認できる。": "phát biểu về mã hóa / khóa",
  "CALS(Commerce At Light Speed)に関する次の記述のうち、本文の内容と一致するものはどれか。": "phát biểu về CALS",
  "コンピュータというと， 一般にはモニタやキーボードを持つパソコンを思い浮かべますが，他にもたくさんの種類があります。": "máy tính không chỉ PC có màn hình/bàn phím",
  "IT とは Information Technology のことを言い，情報技術，もしくは情報通信技術と訳されます。": "phát biểu về truyền thông",
  "オンラインショッピングやネットオークションなど， インターネットを利用して買い物をした経験のある人も多いと思います。": "phát biểu về thương mại điện tử",
  "アルゴリズムは問題毎に検討しなければなりませんが， 重要でよく使われる問題には有効なアルゴリズムが提案されています。": "phát biểu về thuật toán / lập trình",
  "コンピュータは， 1 台で様々な仕事を行うことができる自由度がありますが， このことが逆に悪用される危険性も持っています。": "đa năng máy tính cũng mang rủi ro lạm dụng",
  "真空管第 1 世代の論理素子である真空管は，図 61 のように空気を抜いたガラス管の中にヒータと電極を閉じこめたものです。": "phát biểu về ống chân không",
  "sin，cos，tan のような三角関数や log，exp などの対数，指数関数などは加減乗除に置き換えることができます。": "phát biểu về hàm số / biến đổi số",
  "金属線や光ファイバなどのケーブルで接続できる通信手段としては， CATV， ADSL，FTTH，電灯線通信などが代表的です。": "phát biểu về truyền thông",
  "一般の機械装置では初期故障が多く，その後しばらく安定して稼働し，寿命に近づくと再び故障が増えるというバスタブ曲線を描きます。": "đường cong bathtub (độ tin cậy)",
  "射影と選択を合わせた以下の SQL の例では，「学籍簿」の表から氏名が「香」で終わる人の「氏名」と「出身地」を抜き出します。": "phát biểu về SQL / CSDL",
  "新たなプログラムを作成するときに， 効率的な内部処理とともに考慮しなければならない重要な要素はヒューマンインタフェースです。": "phát biểu về thuật toán / lập trình",
  "Windows， MacOS，Linux などのソフトウェアは， オペレーティングシステム，または略して OS と呼ばれます。": "phát biểu về OS / UI",
  "コンピュータ化によって顧客についての多様な情報をまとめて管理することが容易になり， コピーして複製を残すことが容易になりました。": "máy tính hóa giúp quản lý & sao chép thông tin khách",
  "「13.3 文字の情報量」で述べたように，英数字の情報量は 1 文字につき 1 byte なので，たとえば，123 というデータは…": "lượng tin chữ / 1 byte cho chữ Latin",
  "コンピュータのソフトウェアにはワープロ， 表計算などがありますが， これらは， プログラムという命令の集まりによって記述されています。": "phát biểu về thuật toán / lập trình",
  "コンピュータネットワーク( 以降は単にネットワークと呼びます) とは， 電子機器同士が電気的にデータの送受信をできるようにしたものです。": "phát biểu về topology mạng",
  "ネットワークを介した取引プロセスの電子化のことを電子商取引， または e コマース(Electronic Commerce) と言います。": "phát biểu về topology mạng",
  "データベースのデータを表す単位のことをレコードと言い，レコード間の関係を表す代表的な表現法は階層的表現，網的表現，関係的表現の 3 つです。": "Bản ghi (record); quan hệ: phân cấp / mạng / quan hệ",
  "手続型の言語では，単純な文法で手順を記述しますが，一度作成したプログラムの再利用を容易にするためにオブジェクト指向という概念が考案されました。": "phát biểu về thuật toán / lập trình",
  "デジタルカメラのメモリには「32 ギガバイト」などと書いてあったり， ハードディスクレコーダには「1 テラバイト」などと表示されていたりします。": "phát biểu về ổ cứng",
  "コンピュータでは表のどの部分が一致しているのかを指定する必要があるため，次の例のように WHERE の条件文で「学籍簿.学生証番号 =成績表.。": "SQL JOIN/WHERE: chỉ định cột khớp giữa các bảng",
  "コンピュータとは，記憶して処理する機械ですが，処理する部品が CPU だけなのに対し， 記憶する部品はメモリ， ハードディスクなど多種類あります。": "phát biểu về ổ cứng",
  "ホームページを閲覧するのに， 自宅からアクセスした場合と， ホットスポットなどの外部からアクセスした場合とでは体感速度が大きく異なることがあります。": "phát biểu về web",
  "携帯電話の着信メロディは， 音の高さ， 長さ， 各音符の強弱， 左右バランス， モジュレーションなどにより表現されていて， 高音質な楽曲再生が可能です。": "phát biểu về điện thoại di động",
  "SQL とは，Structured Query Language の頭文字をとったもので，直訳すると構造化された問い合わせ用の言語ということになります。": "phát biểu về SQL / CSDL",
  "この章では， コンピュータネットワークの形態や構成について学習し， 日常的に利用しているインターネットの意味やセキュリティに関する課題を正しく理解します。": "phát biểu về topology mạng",
  "これまでに整数も実数もすべて 2 進数で表現できることを見てきましたが， 2 進数の表現では，1 桁の足し算回路によって任意の数字の足し算が実現できます。": "phát biểu về phép tính / bù 2",
  "ホームページで個人情報を入力する場合， ブラウザに錠のアイコンが出ていて，プロトコルが https になっていることを確認する必要があります（ 図 44 ）。": "phát biểu về web",
  "最近では指紋，静脈，顔，音声などによる生体認証(バイオメトリクス)も利用されていますが，セキュリティ対策にはパスワードが最も重要であることに変わりありません。": "phát biểu về đa phương tiện / nén",
  "オンラインショッピングで買い物をするときに， その都度， 氏名， 住所， 電話番号， カード番号などの個人情報を入力するのは面倒であり，情報漏洩の危険性も増します。": "phát biểu về thương mại điện tử",
  "一般に， 情報が多い少ないと言うとき， その人にとって役に立つかどうかの主観的な判断が入ることがありますが，情報処理の世界では，質を問わずに客観的な量として情報を測ります。": "Lượng tin CNTT đo khách quan, không theo chủ quan",
  "現在のコンピュータの直接の祖先となる電子式計算機に限定すると，コンピュータの歴史は 60 数年程度しかありませんが，通常は使われる論理素子によって 4 世代に分けられています。": "Máy tính điện tử ~60 năm, chia 4 thế hệ theo linh kiện logic",
  "たとえば 5×3 の計算をする場合，5 は 2 進数で 101，3 は 2 進数で 11 なので，筆算で下に書かれた 1 のあるところまで桁をずらして 101 を書いて足せば…": "Ví dụ nhân nhị phân bằng dịch bit và cộng",
  "通信速度のような転送レートを測るときには，1 秒あたりの bit 数で数え，単位としては， bit/sec，もしくは bit per second を略した bps を使います。": "phát biểu về truyền thông",
  "コンサートチケットや電車の指定券の予約は， オンラインで接続されたコンピュータによって処理されています。全国にいる多くの人が同時に予約を入れても二重登録されないようにするために…": "phát biểu về thương mại điện tử",
  "インターネットを流れる情報は， 第三者に見られてしまう危険性があります。 ビジネスに欠かせない道具となっているインターネットには十分なセキュリティ対策が必要になります。この章では…": "Internet có rủi ro bị xem lén — cần bảo mật",
  "半導体を使うと 0 と 1 の 1 桁の足し算が実現できることを学習してきましたが，2 進数の考え方を使うと， この足し算を利用して， 桁数の多い計算や， かけ算， 割り算などの…": "phát biểu về CPU / bộ nhớ / bán dẫn",
  "MP3 プレーヤで聴く音楽やハードディスクレコーダで見る映像はデジタル化されて記録されています。この章では，音楽や映像のデジタル化の仕組みと，マルチメディアの情報量について学習します。": "phát biểu về ổ cứng",
  "BS(Broadcasting Satellite = 放送衛星)とCS(Communication Satellite = 通信衛星)は，どちらも放送用に利用されていることから分かる通り…": "phát biểu về truyền thông",
  "「17 データベース理論」では，データベースの表現法および操作を学びましたが，実際にコンピュータ上で利用するためには，データベースシステムを操作する記述方法を知らなければなりません。この章では…": "Chương SQL/CSDL: cách mô tả thao tác DB",
  "インターネット情報の流れ 家庭のパソコンからインターネットに接続するときには 、 ISP (Internet Service Provider)( 略して プロバイダ とも言います ) と契約し…": "Kết nối Internet qua ISP/provider (đoạn mở đầu)",
};
