/**
 * Full quality upgrade for all unified quiz banks (promt.md structure).
 * Run: node quiz/tools/upgrade_full.mjs
 *
 * - MLN/PRM: fill concept, optionsVi, structured whyWrong
 * - JIT: VI-first polish
 * - FE: rebuild bank300 from BO_300; fix test distractors; datajfe bilingual
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "../..");
const OUT = path.resolve(__dirname, "../data");
const LETTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

function bullets(...lines) {
  return lines
    .filter((l) => l != null && String(l).trim())
    .map((l) => String(l).replace(/^\s*[•\-\*]\s*/, "").trim())
    .filter(Boolean)
    .map((l) => `• ${l}`)
    .join("\n");
}

function writeBank(key, questions, meta = {}) {
  fs.mkdirSync(OUT, { recursive: true });
  const payload = {
    subject: key,
    upgradedAt: new Date().toISOString(),
    count: questions.length,
    ...meta,
    questions,
  };
  fs.writeFileSync(path.join(OUT, `${key}.json`), JSON.stringify(payload));
  fs.writeFileSync(
    path.join(OUT, `${key}.js`),
    `// Auto-generated by quiz/tools/upgrade_full.mjs — full promt pass\n` +
      `window.QUIZ_DATA = window.QUIZ_DATA || {};\n` +
      `window.QUIZ_DATA[${JSON.stringify(key)}] = ${JSON.stringify(questions)};\n`
  );
  console.log(`[ok] ${key}: ${questions.length}`);
}

function loadJsBank(key) {
  const t = fs.readFileSync(path.join(OUT, `${key}.js`), "utf8");
  const m = t.match(/= (\[[\s\S]*\]);\s*$/);
  if (!m) throw new Error("load " + key);
  return Function(`"use strict"; return (${m[1]});`)();
}

function correctLetters(q) {
  if (Array.isArray(q.answers) && q.answers.length) return q.answers.map(String);
  return q.answer ? [String(q.answer)] : [];
}

function shuffleInPlace(arr, seed = 1) {
  let s = seed >>> 0;
  for (let i = arr.length - 1; i > 0; i--) {
    s = (s * 1664525 + 1013904223) >>> 0;
    const j = s % (i + 1);
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// ── Glossary EN → short VI (FE) ─────────────────────────
const GLOSS = {
  bit: "bit (đơn vị nhỏ nhất 0/1)",
  byte: "byte (8 bit)",
  ram: "RAM (bộ nhớ khả biến)",
  rom: "ROM (chỉ đọc, bất biến)",
  sram: "SRAM (thường dùng cho cache)",
  dram: "DRAM (RAM chính)",
  cache: "bộ nhớ đệm",
  cpu: "CPU (bộ xử lý trung tâm)",
  alu: "ALU (đơn vị số học-logic)",
  "control unit": "đơn vị điều khiển",
  "vacuum tube": "ống chân không",
  transistor: "transistor",
  vlsi: "VLSI (tích hợp mật độ rất cao)",
  unicode: "Unicode (mã đa ngôn ngữ)",
  ascii: "ASCII (mã ký tự cơ bản)",
  "batch processing": "xử lý theo lô",
  "real-time": "thời gian thực",
  "real-time processing": "xử lý thời gian thực",
  middleware: "phần mềm trung gian",
  compiler: "trình biên dịch",
  interpreter: "trình thông dịch",
  "assembly language": "hợp ngữ",
  waiting: "trạng thái chờ (I/O/sự kiện)",
  ready: "trạng thái sẵn sàng chờ CPU",
  running: "đang chạy trên CPU",
  terminated: "đã kết thúc",
  suspended: "tạm dừng",
  "hard disk": "ổ cứng",
  ssd: "SSD",
  "drop table": "xóa bảng (cả cấu trúc)",
  "process management": "quản lý tiến trình",
  "input unit": "đơn vị nhập",
  "4th generation": "thế hệ thứ 4",
  "open-source license": "giấy phép mã nguồn mở",
  "circuit switching": "chuyển mạch kênh",
  "packet switching": "chuyển mạch gói",
  "message switching": "chuyển mạch thông điệp",
  tapping: "nghe lén trên đường truyền",
  scavenging: "thu thập dữ liệu còn sót",
  step: "STEP (chuẩn product model)",
  edi: "EDI (trao đổi chứng từ điện tử)",
  router: "bộ định tuyến",
  hub: "hub (tầng vật lý/broadcast)",
  switch: "switch (chuyển mạch khung)",
  "deadlock": "bế tắc",
  "left outer join": "LEFT OUTER JOIN",
  "cartesian product": "tích Descartes",
  "two-phase commit": "cam kết 2 pha",
  "common criteria": "Common Criteria (ISO 15408)",
  "iso 12207": "ISO 12207 (vòng đời phần mềm)",
  servlet: "Java servlet",
  adsl: "ADSL",
  atm: "ATM (cell cố định)",
  hdlc: "HDLC",
  fcs: "FCS (kiểm tra lỗi frame)",
  "dummy activity": "hoạt động giả (thời lượng 0)",
  mirroring: "nhân bản (RAID 1)",
  striping: "chia dải (RAID 0)",
  dma: "DMA (truy cập bộ nhớ trực tiếp)",
  arp: "ARP (IP → MAC)",
  icmp: "ICMP (báo lỗi / ping)",
  octal: "hệ bát phân",
  hexadecimal: "hệ thập lục phân",
  pipeline: "đường ống lệnh",
  "program counter": "bộ đếm chương trình (PC)",
  "non-volatile": "bất biến (không mất khi tắt nguồn)",
  volatile: "khả biến (mất khi tắt nguồn)",
  "centralized processing": "xử lý tập trung",
  "peripheral device": "thiết bị ngoại vi",
  register: "thanh ghi (trong CPU)",
  bcd: "BCD (mỗi chữ số thập phân 4 bit)",
  fpga: "FPGA (lập trình sau sản xuất)",
};

function gloss(en) {
  const k = String(en || "").trim().toLowerCase();
  if (GLOSS[k]) return GLOSS[k];
  // partial
  for (const [a, b] of Object.entries(GLOSS)) {
    if (k.includes(a) && a.length >= 3) return b;
  }
  return String(en || "").trim();
}

function viQuestion(en) {
  const q = String(en || "").trim();
  const rules = [
    [/^How many bits are in one byte\??$/i, "Một byte có bao nhiêu bit?"],
    [/^What is the smallest unit of data/i, "Đơn vị dữ liệu nhỏ nhất trong máy tính là gì?"],
    [/^Which generation introduced VLSI\??$/i, "Thế hệ máy tính nào giới thiệu VLSI?"],
    [/^First-generation logic device\??$/i, "Thiết bị logic thế hệ 1 là gì?"],
    [/^Non-volatile storage example\??$/i, "Ví dụ thiết bị lưu trữ bất biến?"],
    [/^Which memory loses data when power is off\??$/i, "Bộ nhớ nào mất dữ liệu khi tắt nguồn?"],
    [/^Main memory is typically which type\??$/i, "Bộ nhớ chính thường thuộc loại nào?"],
    [/^Cache is usually implemented with\??$/i, "Cache thường được thực hiện bằng gì?"],
    [/^Hexadecimal digit A in decimal\??$/i, "Chữ số hex A bằng bao nhiêu trong hệ thập phân?"],
    [/^Number system using digits 0-7\??$/i, "Hệ đếm dùng các chữ số 0–7 là hệ nào?"],
    [/^International multilingual character code\??$/i, "Bộ mã ký tự đa ngôn ngữ quốc tế là gì?"],
    [/^CPU = which units\??$/i, "CPU gồm những đơn vị nào?"],
    [/^Which is a peripheral device\??$/i, "Cái nào là thiết bị ngoại vi?"],
    [/^Auxiliary storage characteristic\??$/i, "Đặc trưng của bộ nhớ phụ là gì?"],
    [/^RAID 1 main feature\??$/i, "Đặc trưng chính của RAID 1?"],
    [/^RAID 0 main feature\??$/i, "Đặc trưng chính của RAID 0?"],
    [/^Instruction cycle order\??$/i, "Thứ tự chu kỳ lệnh là gì?"],
    [/^PC register holds\??$/i, "Thanh ghi PC giữ gì?"],
    [/^DMA purpose\??$/i, "Mục đích của DMA?"],
    [/^Jobs executed collectively without user interaction\??$/i, "Công việc chạy theo lô, không tương tác user — hệ nào?"],
    [/^Airline reservation immediate response\??$/i, "Đặt vé máy bay cần phản hồi ngay — kiểu xử lý nào?"],
    [/^ARP resolves\??$/i, "ARP phân giải gì?"],
    [/^ICMP used by\??$/i, "ICMP được dùng cho việc gì?"],
    [/^Private IP example\??$/i, "Ví dụ địa chỉ IP riêng (private)?"],
    [/^What is the main purpose of interface design\??$/i, "Mục đích chính của thiết kế giao diện là gì?"],
    [/^A process is waiting for data from a disk/i, "Tiến trình đang chờ dữ liệu từ đĩa — thường ở trạng thái nào?"],
    [/^Which of the following is a non-volatile storage device\??$/i, "Thiết bị nào là lưu trữ bất biến?"],
    [/^Which SQL command removes a table definition and its data\??$/i, "Lệnh SQL nào xóa định nghĩa bảng và dữ liệu?"],
    [/^Which type of software acts as an intermediary/i, "Loại phần mềm nào đóng vai trò trung gian?"],
    [/^A compiler translates a source program/i, "Trình biên dịch dịch chương trình nguồn — đặc trưng nào đúng?"],
    [/^Which OS management function is primarily responsible for deciding which process receives CPU time\??$/i, "Chức năng OS nào quyết định tiến trình nào được CPU?"],
    [/^Why is user-friendly interface design important\??$/i, "Vì sao thiết kế giao diện thân thiện quan trọng?"],
    [/^Which of the following devices was mainly used as the logic gate in first-generation computers\??$/i, "Thế hệ 1 dùng thiết bị nào làm cổng logic?"],
    [/^How many bits are contained in one byte\??$/i, "Một byte chứa bao nhiêu bit?"],
    [/^What is the smallest unit of data representation in computers\??$/i, "Đơn vị biểu diễn dữ liệu nhỏ nhất trong máy tính?"],
  ];
  for (const [re, vi] of rules) if (re.test(q)) return vi;
  // heuristic fragments
  let vi = q
    .replace(/^Which of the following\s*/i, "Cái nào sau đây ")
    .replace(/^Which\s+/i, "Cái nào / ")
    .replace(/^What is\s+/i, "Cái gì là ")
    .replace(/^What are\s+/i, "Những gì là ")
    .replace(/^How many\s+/i, "Bao nhiêu ")
    .replace(/^Why\s+/i, "Vì sao ")
    .replace(/\?$/, "?");
  return vi.length < q.length * 1.8 ? vi : `Dịch gợi ý: ${q}`;
}

// ── Distractor pools by topic ───────────────────────────
const POOLS = {
  size: ["1", "2", "4", "8", "16", "32", "64", "128", "256", "512", "1024", "1000", "2048"],
  gen: ["1st generation", "2nd generation", "3rd generation", "4th generation", "5th generation"],
  mem: ["RAM", "ROM", "SRAM", "DRAM", "Cache", "Register", "Flash", "Hard disk", "SSD", "Magnetic tape"],
  vol: ["Volatile", "Non-volatile", "Read-only", "Write-only"],
  numsys: ["Binary", "Octal", "Decimal", "Hexadecimal", "BCD"],
  cpu: ["ALU", "Control unit", "Register", "Cache", "GPU", "DMA controller"],
  state: ["Running", "Ready", "Waiting", "Terminated", "Suspended", "New"],
  os: ["Process Management", "Memory Management", "File Management", "Device Management", "Security Management"],
  sql: ["SELECT", "INSERT", "UPDATE", "DELETE", "DROP TABLE", "TRUNCATE", "ALTER TABLE", "CREATE TABLE"],
  lang: ["Machine language", "Assembly Language", "C", "Java", "Python", "SQL"],
  compile: [
    "The entire source program is translated before execution",
    "Statements are translated and executed one by one",
    "Only comments are translated",
    "Machine code is converted back to source",
  ],
  lang: [
    "Machine language",
    "Assembly Language",
    "The entire source program is translated before execution",
    "Statements are translated and executed one by one",
    "Only comments are translated",
    "Machine code is converted back to source",
    "High-level language only",
  ],
  soft: [
    "System software",
    "Application software",
    "Middleware",
    "Firmware",
    "Driver",
    "Open-source License",
    "To improve user usability and accessibility",
    "To reduce hardware cost",
    "To minimize storage devices",
    "To remove multimedia functions",
  ],
  net: ["Router", "Hub", "Switch", "Bridge", "Gateway", "Repeater", "Firewall"],
  switch: ["Circuit switching", "Packet switching", "Message switching", "Cell switching"],
  raid: ["Mirroring", "Striping, no redundancy", "Parity striping", "Hot spare only"],
  process: ["Batch processing", "Real-time processing", "Online processing", "Centralized processing", "Distributed processing"],
  crime: ["Tapping", "Scavenging", "Salami method", "Falsification", "Spoofing"],
  std: ["ISO 12207", "ISO 9001", "ISO 14001", "ISO/IEC 15408", "STEP", "EDI", "CORBA", "CALS"],
  db: ["1NF", "2NF", "3NF", "BCNF", "Primary key", "Foreign key", "Cartesian product", "LEFT OUTER JOIN", "INNER JOIN"],
  sec: ["Confidentiality", "Integrity", "Availability", "Authentication", "Authorization", "Non-repudiation"],
  misc: [
    "Reduce hardware cost",
    "Improve user usability and accessibility",
    "Minimize storage devices",
    "Increase CPU temperature",
    "Align IT with business goals",
    "Logs, audits, alerts",
  ],
};

function topicOf(question, answer) {
  const t = `${question} ${answer}`.toLowerCase();
  // Order matters: process state / compile before generic "disk/memory"
  // NOTE: avoid matching "which statement" via "which state"
  if (
    /\b(ready|waiting|running|terminated|suspended)\b|process state|which state is|most likely in\?/i.test(
      t
    )
  )
    return "state";
  if (/deadlock/i.test(t)) return "state";
  if (/compiler|interpreter|assembly language|mnemonic|translated before execution|compilation process/i.test(t))
    return "lang";
  if (/bit|byte|kb|1024|2\^n|bcd|hex|octal|two'?s complement|decimal digit/i.test(t)) return "size";
  if (/generation|vlsi|vacuum tube|transistor/i.test(t)) return "gen";
  if (/drop table|sql command|truncate table/i.test(t)) return "sql";
  if (/sql|join|1nf|2nf|3nf|cartesian|transaction|two-phase commit/i.test(t)) return "db";
  if (/circuit switching|packet switching|message switching/i.test(t)) return "switch";
  if (/router|hub|switch|arp|icmp|\bip\b|mac|tcp|udp|network|lan|token|csma|adsl|hdlc|atm|fdm/i.test(t))
    return "net";
  if (/raid|mirror|stripe/i.test(t)) return "raid";
  if (/batch|real-time|centralized|distributed|payroll|reservation/i.test(t)) return "process";
  if (/open-source|middleware|interface design|usability|license|software acts as/i.test(t)) return "soft";
  if (/tapping|scaveng|salami|falsif|crime|attack/i.test(t)) return "crime";
  if (/iso|step|edi|cmmi|common criteria|servlet/i.test(t)) return "std";
  if (/cpu|alu|control unit|pipeline|dma|pc register|instruction cycle|fetch/i.test(t)) return "cpu";
  if (/security|confiden|integrit|availab|auth/i.test(t)) return "sec";
  if (/ram|rom|sram|dram|cache|memory|volatile|non-volatile|storage|hard disk|ssd|auxiliary|register/i.test(t))
    return "mem";
  if (/process management|os management/i.test(t)) return "os";
  return "misc";
}

function normalizeAnswer(ans) {
  let a = String(ans || "").trim();
  // take first alternative before /
  if (a.includes("/") && a.length > 40) {
    /* keep */
  } else if (a.includes(" / ")) {
    a = a.split(" / ")[0].trim();
  } else if (/ or /i.test(a) && a.length < 80) {
    a = a.split(/ or /i)[0].trim();
  }
  // strip trailing parenthetical dumps
  a = a.replace(/\s*\([^)]{40,}\)\s*$/, "").trim();
  return a;
}

function makeOptions(question, correctRaw, seed) {
  const correct = normalizeAnswer(correctRaw);
  const topic = topicOf(question, correct);
  const primary = shuffleInPlace([...(POOLS[topic] || POOLS.misc)], seed);
  const fallback = shuffleInPlace(
    [
      ...POOLS.misc,
      ...POOLS.mem,
      ...POOLS.cpu,
      ...POOLS.os,
      ...POOLS.soft,
    ].filter((x) => !(POOLS[topic] || []).includes(x)),
    seed + 3
  );
  const wrong = [];
  const seen = new Set([correct.toLowerCase()]);

  const tryAdd = (c) => {
    const t = String(c || "").trim();
    if (!t || seen.has(t.toLowerCase())) return false;
    if (t.toLowerCase() === correct.toLowerCase()) return false;
    // too substring-similar
    if (t.length > 3 && correct.toLowerCase().includes(t.toLowerCase())) return false;
    if (correct.length > 3 && t.toLowerCase().includes(correct.toLowerCase())) return false;
    seen.add(t.toLowerCase());
    wrong.push(t);
    return true;
  };

  // numeric distractors (same "topic" of numbers)
  if (/^-?\d+(\.\d+)?$/.test(correct.replace(/,/g, ""))) {
    const n = Number(String(correct).replace(/,/g, ""));
    for (const d of [n + 1, n - 1, n * 2, Math.round(n / 2), 0, 1, 2, 4, 8, 16, 10, 32, 64]) {
      if (!Number.isFinite(d) || d === n) continue;
      tryAdd(String(d));
      if (wrong.length >= 3) break;
    }
  }

  // generation-style
  if (/generation|th generation|st generation|nd generation|rd generation/i.test(correct + question)) {
    for (const g of shuffleInPlace(POOLS.gen.slice(), seed)) tryAdd(g);
  }

  // process states
  if (topic === "state" || /waiting|ready|running|terminated|suspended/i.test(correct)) {
    for (const s of primary) tryAdd(s);
  }

  for (const cand of primary) {
    if (wrong.length >= 3) break;
    tryAdd(cand);
  }
  for (const cand of fallback) {
    if (wrong.length >= 3) break;
    tryAdd(cand);
  }
  let i = 0;
  while (wrong.length < 3) tryAdd(`Phương án nhiễu ${++i}`);

  const opts = shuffleInPlace([correct, wrong[0], wrong[1], wrong[2]], seed + 7);
  const options = {};
  let answer = "A";
  opts.forEach((t, i) => {
    options[LETTERS[i]] = t;
    if (t === correct) answer = LETTERS[i];
  });
  return { options, answer, topic };
}

function whatIsFor(opt) {
  return gloss(opt);
}

function buildExplain({ question, options, answer, detail, tip, keywords }) {
  const ansText = options[answer];
  const ansVi = gloss(ansText);
  const qVi = viQuestion(question);
  const concept =
    tip && !/^Ôn:\s*/i.test(tip)
      ? tip
      : detail && detail.length > 8 && detail !== `Đáp án: ${ansText}.`
        ? detail
        : `${ansVi} là đáp án đúng.`;
  const whyLines = [
    `Chọn ${answer} — ${ansText}${ansVi !== ansText ? ` (${ansVi})` : ""}.`,
  ];
  if (detail && detail !== ansText && detail !== `Đáp án: ${ansText}.` && detail !== concept) {
    whyLines.push(detail);
  }
  if (tip && tip !== detail && tip !== concept && !whyLines.includes(tip)) {
    whyLines.push(tip);
  } else if (keywords && !tip) {
    whyLines.push(`Từ khóa ôn: ${keywords}`);
  }
  // one more conceptual line for short numeric/term answers
  if (whyLines.length < 2) {
    whyLines.push(`Khớp định nghĩa/chuẩn kiến thức FE cho câu hỏi này.`);
  }
  const whyCorrect = bullets(...whyLines);
  const optionsVi = {};
  const whatIs = {};
  const whyWrong = {};
  Object.keys(options).forEach((L) => {
    optionsVi[L] = gloss(options[L]);
    whatIs[L] = optionsVi[L];
    if (L === answer) return;
    whyWrong[L] = bullets(
      `Là gì? ${whatIs[L]}`,
      `Vì sao sai? Sai trong ngữ cảnh câu hỏi này vì cần «${ansText}», không phải «${options[L]}».`
    );
  });
  // contrast pairs
  const pairs = [
    [/waiting/i, /ready/i, "Ready chỉ chờ CPU; Waiting/Blocked đang chờ I/O hoặc sự kiện."],
    [/ready/i, /waiting/i, "Waiting đang chờ sự kiện; Ready đã sẵn sàng chạy khi có CPU."],
    [/compiler|toàn bộ|before execution/i, /interpret|one by one|từng/i, "Interpreter dịch-chạy từng lệnh; compiler dịch cả chương trình trước."],
    [/circuit switching/i, /packet/i, "Packet switching không dành riêng kênh cố định trước khi truyền."],
    [/packet switching/i, /circuit/i, "Circuit switching thiết lập path dành riêng — khác mô hình gói."],
    [/drop table/i, /delete|truncate/i, "DELETE/TRUNCATE không xóa định nghĩa bảng như DROP TABLE."],
    [/non-volatile|hard disk|ssd|rom/i, /ram|cache|register/i, "RAM/cache/register thường mất dữ liệu khi tắt nguồn (volatile)."],
    [/ram|volatile/i, /rom|hard disk|ssd/i, "ROM/ổ đĩa thường giữ dữ liệu khi tắt nguồn."],
    [/tapping/i, /scaveng/i, "Scavenging lấy residual data; tapping nghe lén trên đường truyền."],
    [/open-source/i, /proprietar|closed/i, "Giấy phép đóng không cho tự do xem/sửa/phân phối mã nguồn."],
    [/unicode/i, /ascii/i, "ASCII hẹp; Unicode đa ngôn ngữ."],
    [/4th|vlsi/i, /1st|vacuum/i, "VLSI gắn thế hệ 4; ống chân không là thế hệ 1."],
    [/middleware/i, /application software|os\b/i, "Middleware là lớp trung gian, không thay OS hay app thuần."],
  ];
  Object.keys(options).forEach((L) => {
    if (L === answer) return;
    for (const [aRe, oRe, why] of pairs) {
      if (aRe.test(ansText) && oRe.test(options[L])) {
        whyWrong[L] = bullets(`Là gì? ${whatIs[L]}`, `Vì sao sai? ${why}`);
        break;
      }
    }
  });

  return {
    questionVi: qVi,
    optionsVi,
    answerDisplay: `${answer}. ${ansText}`,
    concept: String(concept).length > 240 ? String(concept).slice(0, 240) + "…" : String(concept),
    whyCorrect,
    whyWrong,
    whatIs,
  };
}

// ── Parse BO 300 ────────────────────────────────────────
function parseBO300() {
  const text = fs.readFileSync(path.join(ROOT, "wedJfe/BO_300_CAU_ON_THI.txt"), "utf8");
  const re = /Cau\s+(\d+)\.\s*([\s\S]*?)(?=Cau\s+\d+\.|={5,}|$)/gi;
  const out = [];
  let m;
  while ((m = re.exec(text))) {
    const num = Number(m[1]);
    const body = m[2].trim();
    const lines = body.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
    const q = lines[0] || "";
    let ans = "";
    let kw = "";
    for (const line of lines) {
      const am = line.match(/^Đáp án:\s*(.+)$/i);
      if (am) ans = am[1].trim();
      const km = line.match(/^\(Tu khoa[^:]*:\s*(.+)\)$/i);
      if (km) kw = km[1].trim();
    }
    if (!q || !ans) continue;
    out.push({ num, question: q, answer: ans, keywords: kw });
  }
  return out;
}

// ── Parse test.txt (Q + answer + detail) ────────────────
function parseTestTxt() {
  const text = fs.readFileSync(path.join(ROOT, "wedJfe/test.txt"), "utf8");
  const map = new Map(); // question lower -> {answer, detail}
  const re =
    /Câu hỏi\s+\d+:\s*(.+?)\s*\nĐáp án:\s*(.+?)(?=\nCâu hỏi|\nDưới đây|$)/gs;
  let m;
  while ((m = re.exec(text))) {
    const question = m[1].replace(/\s+/g, " ").trim();
    const ansBlock = m[2].replace(/\s+/g, " ").trim();
    const pm = ansBlock.match(/^(.+?)(\s*\((.+)\))?\s*$/);
    const label = (pm ? pm[1] : ansBlock).replace(/\s*\(.+$/, "").trim();
    const detail = pm && pm[3] ? pm[3].trim() : ansBlock;
    map.set(question.toLowerCase(), { question, answer: label, detail });
  }
  return map;
}

// ── datajfe from md ─────────────────────────────────────
const DATAJFE_ANSWERS = {
  1: 3, 2: 0, 3: 0, 4: 3, 5: 3, 7: 2, 8: 0, 9: 3, 10: 2, 11: 3, 12: 3, 13: 3,
  14: 3, 15: 2, 16: 3, 17: 0, 18: 3, 19: 0, 20: 1, 21: 1, 22: 2, 23: 3, 24: 0,
  25: 3, 26: 0, 27: 0, 28: 1, 29: 2, 30: 1, 31: 0, 32: 0, 33: 0, 34: 3, 35: 2,
  36: 1, 37: 2, 38: 3, 39: 2, 40: 2, 41: 3, 44: 1,
};
const DATAJFE_SKIP = new Set([6, 42, 43]);
const DATAJFE_TIPS = {
  1: "Token ring/token bus chỉ gửi khi có token — khác CSMA/CD tranh chấp kênh.",
  2: "STEP (ISO 10303) là chuẩn trao đổi product model.",
  3: "Circuit switching: kênh dành riêng trước khi truyền; dễ lãng phí khi traffic bursty.",
  4: "Rút ngắn activity chỉ ảnh hưởng deadline nếu nằm trên critical path.",
  5: "Tapping = nghe lén/chặn dữ liệu trên đường truyền mà không nhất thiết sửa.",
  7: "ISO 12207: khung quy trình vòng đời PM, không bắt buộc method cụ thể.",
  8: "Servlet: chương trình Java chạy trên application server, đáp request client.",
  9: "ISO/IEC 15408 Common Criteria: khung yêu cầu & đánh giá bảo mật độc lập.",
  10: "CMMI Level 2 Managed: quản theo dự án; chưa chuẩn hóa toàn tổ chức.",
  11: "Phụ thuộc transitive giữa non-key → chưa đạt 3NF.",
  12: "HDLC: frame, bit stuffing, full-duplex.",
  13: "Message digest dùng phát hiện falsification (toàn vẹn).",
  14: "Shareware: dùng thử miễn phí, trả phí nếu tiếp tục.",
  15: "ATM: cell độ dài cố định, virtual circuit, hỗ trợ QoS.",
  16: "Message switching: store-and-forward, hỗ trợ khác tốc độ.",
  17: "Xóa nút BST thường lấy inorder successor (nhỏ nhất cây con phải).",
  18: "Message authentication phát hiện document bị sửa.",
  19: "LEFT OUTER JOIN giữ mọi dòng bảng trái.",
  20: "Scavenging: lấy residual data sau job — không phải chặn trên mạng.",
  21: "CROSS JOIN / Cartesian: mọi cặp hàng.",
  22: "Deadlock: hai transaction chờ khóa lẫn nhau.",
  23: "FDM: chia tần số; guardband giảm nhiễu giữa kênh.",
  24: "ADSL: Internet qua đường điện thoại; download thường > upload.",
  25: "Dummy activity: chỉ quan hệ phụ thuộc, thời lượng 0.",
  26: "M/M/1 giả định service time exponential (không cố định).",
  27: "M/M/1 giả định FCFS; priority phá giả định đó.",
  28: "Ready = chờ CPU; có thể nhiều process trong ready queue.",
  29: "Mã hóa bằng public key người nhận → giải bằng private key người nhận.",
  30: "Linear search best case: 1 lần so sánh (phần tử ở đầu).",
  31: "Two-phase commit giữ toàn vẹn cập nhật phân tán.",
  32: "Hết repeated group = 1NF; partial dependency → chưa 2NF.",
  33: "Availability (CIA): truy cập thông tin khi cần.",
  34: "Data Link: frame, phát hiện lỗi, địa chỉ vật lý.",
  35: "Chuyển sang kiểm soát quy trình định lượng (hướng mức cao hơn).",
  36: "Backward pass: lấy giá trị nhỏ hơn khi nhánh phân kỳ.",
  37: "Logical error → roll-back bằng pre-update log.",
  38: "Router: định tuyến giữa mạng logic, tầng Network.",
  39: "FCS trong HDLC: mã kiểm soát lỗi frame.",
  40: "Khóa bí mật đối xứng phải được giữ bí mật.",
  41: "Class C: host hợp lệ; .0 network, .255 broadcast; 256 invalid.",
  44: "Ready state: chờ CPU; nhiều process có thể xếp hàng ready.",
};
const DATAJFE_QVI = {
  1: "Phương thức truy cập LAN tuần hoàn quyền điều khiển theo một hướng cố định. Trạm chỉ gửi sau khi nhận quyền. Cách nào phân biệt tốt nhất với CSMA/CD?",
  2: "Tổ chức muốn trao đổi product model theo chuẩn quốc tế chuyên cho thông tin mô hình sản phẩm. Cơ chế nào phù hợp nhất?",
  3: "Phương thức truyền thiết lập đường dành riêng trước khi gửi; hiệu năng dự đoán được nhưng traffic bursty lãng phí dung lượng. Đây là switching nào?",
  4: "Rút ngắn activity không nằm critical path mà ngày hoàn thành dự án không đổi. Giải thích nào đúng nhất?",
  5: "Kẻ tấn công bí mật chặn dữ liệu trên mạng và đánh cắp thông tin, không nhất thiết sửa dữ liệu. Tội/kiểu tấn công nào?",
  7: "Chuẩn quốc tế cấu trúc quy trình vòng đời (acquisition…maintenance) nhưng không bắt buộc method cụ thể?",
  8: "Giải thích phù hợp về Java servlet?",
  9: "Khung chỉ định yêu cầu bảo mật, vendor claim, lab đánh giá độc lập — chuẩn nào?",
};

function parseDatajfeMd(text) {
  text = text.replace(/log\s*\n\s*2\s*\n\s*.?\s*\n\s*N/gi, "log2 N");
  const parts = text.split(/(?=(?:^|\n)image(?:_\d+)?\.png)/i);
  const out = [];
  for (const p0 of parts) {
    const p = p0.trim();
    if (!p) continue;
    const mimg = p.match(/^(image(?:_\d+)?\.png)/i);
    if (!mimg) continue;
    const img = mimg[1];
    let key = 1;
    const mk = img.match(/image_(\d+)\.png/i);
    if (mk) key = Number(mk[1]);
    const rest = p.slice(mimg[0].length).trim();
    const lines = rest.split(/\r?\n/);
    let q = null;
    const opts = [];
    let i = 0;
    while (i < lines.length) {
      const line = lines[i].trim();
      if (/^Câu hỏi:|^Cau hoi:/i.test(line)) {
        q = line.replace(/^Câu hỏi:\s*|^Cau hoi:\s*/i, "").trim();
        i++;
        while (i < lines.length && !lines[i].trim()) i++;
        let buf = [];
        while (i < lines.length) {
          const s = lines[i].trim();
          if (/^image(?:_\d+)?\.png/i.test(s)) break;
          if (/^Dưới đây|^Duoi day/i.test(s)) break;
          if (!s) {
            if (buf.length) {
              opts.push(buf.join(" ").replace(/\s+/g, " ").trim());
              buf = [];
            }
            i++;
            continue;
          }
          buf.push(s.replace(/^[a-dA-D]\)\s*/, ""));
          i++;
        }
        if (buf.length) opts.push(buf.join(" ").replace(/\s+/g, " ").trim());
        break;
      }
      i++;
    }
    if (q && opts.length) {
      out.push({
        img,
        key,
        q,
        opts: opts
          .map((o) => (/log\s*2\s*N|log2\s*N/i.test(o) ? "log₂ N" : o))
          .filter(Boolean),
      });
    }
  }
  return out;
}

// ── Upgrade MLN / PRM ───────────────────────────────────
function upgradeExplainGeneric(q, { isViStem = false } = {}) {
  const exp = { ...(q.explanation || {}) };
  const options = q.options || {};
  const corrects = new Set(correctLetters(q));
  const ans = [...corrects][0] || "A";

  if (!exp.optionsVi || !Object.keys(exp.optionsVi).length) {
    exp.optionsVi = { ...options };
  }
  if (!exp.questionVi || !String(exp.questionVi).trim()) {
    exp.questionVi = isViStem ? q.question : viQuestion(q.question);
  }
  if (!exp.answerDisplay) {
    exp.answerDisplay = corrects
      .map((L) => `${L}. ${exp.optionsVi[L] || options[L] || L}`)
      .join(" | ");
  }
  if (!exp.concept || !String(exp.concept).trim()) {
    const src = exp.whyCorrect || exp.answerDisplay || "";
    exp.concept = String(src)
      .replace(/^【Khái niệm】/, "")
      .split(/\n/)[0]
      .replace(/^•\s*/, "")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 220);
  }
  if (exp.whyCorrect && !String(exp.whyCorrect).includes("•")) {
    const parts = String(exp.whyCorrect)
      .split(/\n+/)
      .map((s) => s.trim())
      .filter(Boolean);
    exp.whyCorrect = bullets(...(parts.length ? parts : [exp.whyCorrect]));
  }
  exp.whyWrong = exp.whyWrong || {};
  exp.whatIs = exp.whatIs || {};
  Object.keys(options).forEach((L) => {
    exp.whatIs[L] = exp.optionsVi[L] || options[L];
    if (corrects.has(L)) return;
    const old = String(exp.whyWrong[L] || "").trim();
    if (/Là gì\?/i.test(old)) {
      exp.whyWrong[L] = old.startsWith("•") ? old : bullets(old);
      return;
    }
    const reason =
      old ||
      `Sai trong ngữ cảnh câu hỏi này vì không phải đáp án đúng (${[...corrects].join("/")}).`;
    exp.whyWrong[L] = bullets(`Là gì? ${exp.whatIs[L]}`, `Vì sao sai? ${reason}`);
  });
  // strip memoryTip to match promt "không thêm mẹo" — keep if present but optional
  return { ...q, explanation: exp };
}

// ── FE build full ───────────────────────────────────────
function buildFeFull() {
  const out = [];
  let id = 1;

  // TEST: from existing + test.txt details + new distractors
  const prev = loadJsBank("fe");
  const testMap = parseTestTxt();
  const testItems = prev.filter((q) => q.task === "test");
  for (const item of testItems) {
    const hit = testMap.get(String(item.question || "").toLowerCase());
    const correctFrom =
      hit?.answer ||
      item.options?.[item.answer] ||
      Object.values(item.options || {})[0];
    const detail = hit?.detail || item.explanation?.concept || "";
    const { options, answer } = makeOptions(item.question, correctFrom, id * 13);
    const explanation = buildExplain({
      question: item.question,
      options,
      answer,
      detail,
      tip: detail,
      keywords: "",
    });
    // prefer richer questionVi from rules
    if (hit) explanation.questionVi = viQuestion(item.question);
    out.push({
      id: id++,
      task: "test",
      taskLabel: "Test",
      num: id - 1,
      question: item.question,
      options,
      answer,
      alternatives: [],
      explanation,
      meta: { rebuilt: true, originId: item.meta?.originId || item.id },
    });
  }

  // BANK300 from BO file
  const bo = parseBO300();
  if (bo.length !== 300) console.warn("BO count", bo.length);
  for (const row of bo) {
    const { options, answer } = makeOptions(row.question, row.answer, row.num * 17 + 3);
    const tip = row.keywords ? `Ôn: ${row.keywords}` : "";
    const explanation = buildExplain({
      question: row.question,
      options,
      answer,
      detail: `Đáp án: ${normalizeAnswer(row.answer)}.`,
      tip,
      keywords: row.keywords,
    });
    out.push({
      id: id++,
      task: "bank300",
      taskLabel: "300 câu",
      num: row.num,
      question: row.question,
      options,
      answer,
      alternatives: [],
      explanation,
      meta: { rebuilt: true, source: "BO_300" },
    });
  }

  // DATAJFE
  const md = fs.readFileSync(path.join(ROOT, "datajfe.md"), "utf8");
  const blocks = parseDatajfeMd(md);
  let n = 0;
  for (const b of blocks) {
    if (DATAJFE_SKIP.has(b.key)) continue;
    if (!(b.key in DATAJFE_ANSWERS)) continue;
    const ci = DATAJFE_ANSWERS[b.key];
    if (ci < 0 || ci >= b.opts.length) continue;
    const options = {};
    b.opts.forEach((t, i) => {
      options[LETTERS[i]] = t;
    });
    const answer = LETTERS[ci];
    const tip = DATAJFE_TIPS[b.key] || "";
    const explanation = buildExplain({
      question: b.q,
      options,
      answer,
      detail: tip,
      tip,
      keywords: "",
    });
    if (DATAJFE_QVI[b.key]) explanation.questionVi = DATAJFE_QVI[b.key];
    else explanation.questionVi = viQuestion(b.q);
    // better optionsVi for long EN options: short vi tip only for answer
    Object.keys(options).forEach((L) => {
      if (L === answer && tip) {
        explanation.optionsVi[L] = tip.length < 120 ? tip : gloss(options[L]);
      } else {
        explanation.optionsVi[L] = gloss(options[L]);
        // if gloss returned same long text, prefix
        if (explanation.optionsVi[L] === options[L] && options[L].length > 80) {
          explanation.optionsVi[L] = options[L].slice(0, 90) + "…";
        }
      }
    });
    n++;
    out.push({
      id: id++,
      task: "datajfe",
      taskLabel: "datajfe",
      num: n,
      question: b.q,
      options,
      answer,
      alternatives: [],
      explanation,
      meta: { imageKey: b.key, img: b.img, rebuilt: true },
    });
  }

  writeBank("fe", out, {
    tasks: ["test", "bank300", "datajfe"],
    note: "full upgrade: BO_300 rebuild + test distractors + datajfe",
  });
  return out.length;
}

// ── JIT polish ──────────────────────────────────────────
function upgradeJit() {
  const qs = loadJsBank("jit").map((q) => {
    const u = upgradeExplainGeneric(q, { isViStem: false });
    const exp = u.explanation;
    if (!exp.questionVi) exp.questionVi = q.explanation?.questionVi || "";
    exp.concept = String(exp.concept || "")
      .replace(/^•\s*/, "")
      .trim();
    const ans = q.answer;
    const ansVi = exp.optionsVi?.[ans] || q.options?.[ans] || ans;
    const lines = String(exp.whyCorrect || "")
      .split("\n")
      .map((s) => s.replace(/^•\s*/, "").trim())
      .filter(Boolean);
    const head = `Chọn ${ans} — ${ansVi}.`;
    const rest = lines.filter((l) => !/^Chọn\s+[A-Z]\s*[—\-]/.test(l));
    exp.whyCorrect = bullets(head, ...rest.slice(0, 4));
    // ensure every wrong option structured
    Object.keys(q.options || {}).forEach((L) => {
      if (L === ans) return;
      const wi = exp.whatIs?.[L] || exp.optionsVi?.[L] || q.options[L];
      const old = String(exp.whyWrong?.[L] || "");
      if (!/Vì sao sai\?/i.test(old)) {
        exp.whyWrong[L] = bullets(
          `Là gì? ${wi}`,
          `Vì sao sai? Sai trong ngữ cảnh câu hỏi này vì cần «${ansVi}», không phải «${exp.optionsVi?.[L] || q.options[L]}».`
        );
      }
    });
    return { ...u, explanation: exp };
  });
  writeBank("jit", qs, { tasks: ["quiz", "sample", "pt"] });
}

function upgradeMln() {
  const qs = loadJsBank("mln").map((q) => upgradeExplainGeneric(q, { isViStem: true }));
  writeBank("mln", qs, { tasks: ["all"] });
}

function upgradePrm() {
  const qs = loadJsBank("prm").map((q) => upgradeExplainGeneric(q, { isViStem: false }));
  writeBank("prm", qs, { tasks: ["fe", "re"] });
}

function main() {
  console.log("Full upgrade starting…");
  upgradePrm();
  upgradeMln();
  upgradeJit();
  buildFeFull();

  // metrics
  for (const k of ["prm", "mln", "jit", "fe"]) {
    const qs = loadJsBank(k);
    let full = 0;
    for (const q of qs) {
      const e = q.explanation || {};
      const nOpt = Object.keys(q.options || {}).length;
      const nW = Object.keys(e.whyWrong || {}).length;
      if (e.concept && e.whyCorrect && nW >= nOpt - 1 && e.answerDisplay) full++;
    }
    console.log(`  metric ${k}: fullForm ${full}/${qs.length}`);
  }
  console.log("Done.");
}

main();
